/* Use USERPROFILE_LATEST to identify
users with Sage-related emails;
track daily frequency with which a particular user
downloads data from the AD Knowledge Portal*/

CREATE OR REPLACE VIEW SAGE.AD.USER_FREQUENCY AS
WITH USER AS (
    SELECT
        ID AS USER_ID,
        CASE
            WHEN
                EMAIL NOT ILIKE '%@sagebase.org'
                AND EMAIL NOT ILIKE '%@sagebionetworks.org'
                THEN 'FALSE'
            ELSE 'TRUE'
        END AS SAGE_INTERNAL
    FROM
        SYNAPSE_DATA_WAREHOUSE.SYNAPSE.USERPROFILE_LATEST
),

DAILY_USER AS (
    SELECT
        USER_ID,
        RECORD_DATE,
        count(DISTINCT FILE_HANDLE_ID) AS NUMBER_OF_UNIQUE_FILES_DOWNLOADED
    FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.FILEDOWNLOAD
    WHERE
        PROJECT_ID = '2580853'
    GROUP BY
        USER_ID, RECORD_DATE
)

SELECT
    DAILY_USER.USER_ID,
    USER.SAGE_INTERNAL,
    DAILY_USER.RECORD_DATE,
    DAILY_USER.NUMBER_OF_UNIQUE_FILES_DOWNLOADED
FROM DAILY_USER
LEFT JOIN USER ON DAILY_USER.USER_ID = USER.USER_ID
ORDER BY
    DAILY_USER.RECORD_DATE DESC,
    DAILY_USER.NUMBER_OF_UNIQUE_FILES_DOWNLOADED DESC;
