USE ROLE PUBLIC;
USE WAREHOUSE COMPUTE_ORG;
USE DATABASE SYNAPSE_DATA_WAREHOUSE;
USE SCHEMA SYNAPSE_RAW;

// Explore certified quiz / certified quiz questions
SELECT *
FROM CERTIFIEDQUIZ
LIMIT 10;

SELECT sum(NUM_TIMES_QUIZ)
FROM
    (
        SELECT
            USER_ID,
            count(*) AS NUM_TIMES_QUIZ
        FROM CERTIFIEDQUIZ GROUP BY USER_ID
    ) AS S
WHERE NUM_TIMES_QUIZ > 1;

SELECT *
FROM
    CERTIFIEDQUIZQUESTION
LIMIT 10;

SELECT DISTINCT INSTANCE
FROM CERTIFIEDQUIZ;
SELECT count(*) AS ROW_COUNT
FROM CERTIFIEDQUIZ;

SELECT *
FROM CERTIFIEDQUIZQUESTIONRECORDS
LIMIT 10;

SELECT
    RESPONSE_ID,
    INSTANCE,
    count(*) AS RESPONSE_COUNT
FROM CERTIFIEDQUIZQUESTION
GROUP BY RESPONSE_ID, INSTANCE
ORDER BY RESPONSE_ID ASC;

SELECT *
FROM CERTIFIEDQUIZQUESTION
WHERE RESPONSE_ID = 1
ORDER BY QUESTION_INDEX ASC;

WITH NO_DUPS AS (
    SELECT DISTINCT * FROM CERTIFIEDQUIZQUESTION
)

SELECT count(*) AS DUP_COUNTS
FROM NO_DUPS;

// Look for whether or not certain API calls are still used
SELECT DISTINCT USER_AGENT
FROM PROCESSEDACCESS
WHERE REQUEST_URL LIKE '%/table/sql/transform';

//110486
SELECT count(*) AS ROW_COUNT
FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.USER_CERTIFIED
WHERE PASSED IS null;

SELECT
    PASSED,
    count(*) AS PASSED_COUNT
FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.USER_CERTIFIED
GROUP BY PASSED;

// This doesn't have me...
SELECT *
FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW.CERTIFIEDQUIZ
WHERE USER_ID = 3324230;

SELECT *
FROM table(SHOW TABLES IN SCHEMA SAGE.PORTAL_RAW);

SHOW TABLES IN SCHEMA SAGE.PORTAL_RAW;
SELECT * FROM table(result_scan(last_query_id()));

SELECT *
FROM SAGE.INFORMATION_SCHEMA.TABLES
WHERE
    TABLE_SCHEMA = 'PORTAL_RAW'
    AND TABLE_NAME = 'NF';
