-- This was a small query put together for https://sagebionetworks.jira.com/browse/SYNSD-893
-- The query is looking for files that have a different name than the entity they are associated with
USE ROLE DATA_ENGINEER;
USE WAREHOUSE COMPUTE_XSMALL;
USE DATABASE SYNAPSE_DATA_WAREHOUSE;
USE SCHEMA SYNAPSE;

-- This is looking by parent_ID
SELECT
    ENTITY_LATEST.ID,
    ENTITY_LATEST.NAME,
    FILE_LATEST.FILE_NAME,
    FILE_LATEST.CONTENT_MD5
FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.NODE_LATEST AS ENTITY_LATEST
INNER JOIN
    SYNAPSE_DATA_WAREHOUSE.SYNAPSE.FILE_LATEST AS FILE_LATEST
    ON
        ENTITY_LATEST.FILE_HANDLE_ID = FILE_LATEST.ID
WHERE
    ENTITY_LATEST.PARENT_ID = 51286684
    AND FILE_LATEST.FILE_NAME != ENTITY_LATEST.NAME
