USE ROLE SYSADMIN;
USE DATABASE GENIE;
USE WAREHOUSE COMPUTE_ORG;

// GENIE user management
// List out all GENIE teams
SELECT DISTINCT
    ID,
    NAME
FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.TEAM_LATEST
WHERE NAME ILIKE '%genie%';

// Get all members that are part of GENIE teams

CREATE OR REPLACE VIEW GENIE.PUBLIC.GENIE_MEMBERS AS (
    WITH GENIE_MEM AS (
        // Only grab team members that are part of the GENIE teams
        SELECT *
        FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.TEAMMEMBER_LATEST
        WHERE TEAM_ID IN (
            SELECT DISTINCT ID
            FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.TEAM_LATEST
            WHERE NAME ILIKE '%genie%'
        )
    ),

    TEAM_LATEST AS (
        SELECT
            ID,
            NAME
        FROM SYNAPSE_DATA_WAREHOUSE.SYNAPSE.TEAM_LATEST
    )

    SELECT
        GENIE_MEM.*,
        TEAM_LATEST.*
    FROM GENIE_MEM
    // Join to get the team name
    LEFT JOIN TEAM_LATEST
        ON GENIE_MEM.TEAM_ID = TEAM_LATEST.ID
);

SELECT
    NAME,
    count(*) AS NUMBER_OF_MEMBERS
FROM GENIE.PUBLIC.GENIE_MEMBERS
GROUP BY NAME;

-- In athena
-- with test as (
--     with genie_mem AS (
--         select *
--         from "teammembersnapshots"
--         where TEAM_ID in (
--             SELECT distinct ID
--             FROM "teamsnapshots"
--             WHERE lower(name) like '%genie%'
--         )
--     )
--     select distinct genie_mem.team_id, genie_mem.member_id, team_latest.name from genie_mem
--     left join (
--         select ID, name from "teamsnapshots"
--     ) team_latest
--     on genie_mem.team_id = team_latest.id
-- )
-- select name, count(*) from test group by name;

SELECT
    CLIN13_1.SAMPLE_ID AS SAMPLE_ID,
    coalesce(CLIN1.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_1_0_1,
    coalesce(CLIN2.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_2_0_1,
    coalesce(CLIN3.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_3_0_0,
    coalesce(CLIN4.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_4_0,
    coalesce(CLIN4_1.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_4_1,
    coalesce(CLIN5.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_5_0,
    coalesce(CLIN6.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_6,
    coalesce(CLIN6_1.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_6_1,
    coalesce(CLIN6_2.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_6_2,
    coalesce(CLIN7.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_7,
    coalesce(
        CLIN8.SAMPLE_ID IS NOT NULL OR CLIN8_1.SAMPLE_ID IS NOT NULL, FALSE
    ) AS PUBLIC_8,
    coalesce(
        CLIN9.SAMPLE_ID IS NOT NULL OR CLIN9_1.SAMPLE_ID IS NOT NULL, FALSE
    ) AS PUBLIC_9,
    coalesce(
        CLIN10.SAMPLE_ID IS NOT NULL OR CLIN10_1.SAMPLE_ID IS NOT NULL, FALSE
    ) AS PUBLIC_10,
    coalesce(
        CLIN11.SAMPLE_ID IS NOT NULL OR CLIN11_1.SAMPLE_ID IS NOT NULL, FALSE
    ) AS PUBLIC_11,
    coalesce(
        CLIN12.SAMPLE_ID IS NOT NULL OR CLIN12_1.SAMPLE_ID IS NOT NULL, FALSE
    ) AS PUBLIC_12,
    coalesce(CLIN13.SAMPLE_ID IS NOT NULL, FALSE) AS PUBLIC_13
FROM GENIE.PUBLIC_01_0_1.CLINICAL AS CLIN1
FULL OUTER JOIN GENIE.PUBLIC_02_0_1.CLINICAL_SAMPLE AS CLIN2
    ON CLIN1.SAMPLE_ID = CLIN2.SAMPLE_ID
FULL OUTER JOIN GENIE.PUBLIC_03_0_0.CLINICAL_SAMPLE AS CLIN3
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_04_0.CLINICAL_SAMPLE AS CLIN4
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_04_1.CLINICAL_SAMPLE AS CLIN4_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_05_0.CLINICAL_SAMPLE AS CLIN5
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_06_0.CLINICAL_SAMPLE AS CLIN6
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_06_1.CLINICAL_SAMPLE AS CLIN6_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_06_2.CLINICAL_SAMPLE AS CLIN6_2
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_07_0.CLINICAL_SAMPLE AS CLIN7
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_08_0.CLINICAL_SAMPLE AS CLIN8
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_08_1.CLINICAL_SAMPLE AS CLIN8_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_09_0.CLINICAL_SAMPLE AS CLIN9
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_09_1.CLINICAL_SAMPLE AS CLIN9_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_10_0.CLINICAL_SAMPLE AS CLIN10
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_10_1.CLINICAL_SAMPLE AS CLIN10_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_11_0.CLINICAL_SAMPLE AS CLIN11
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_11_1.CLINICAL_SAMPLE AS CLIN11_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_12_0.CLINICAL_SAMPLE AS CLIN12
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_12_1.CLINICAL_SAMPLE AS CLIN12_1
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_13_0.CLINICAL_SAMPLE AS CLIN13
    USING (SAMPLE_ID)
FULL OUTER JOIN GENIE.PUBLIC_13_1.CLINICAL_SAMPLE AS CLIN13_1
    USING (SAMPLE_ID);
