USE ROLE PUBLIC;
USE WAREHOUSE COMPUTE_ORG;
USE DATABASE SYNAPSE_DATA_WAREHOUSE;
USE SCHEMA SYNAPSE;

// Distinct client calls this month
SELECT DISTINCT CLIENT
FROM PROCESSEDACCESS
WHERE DATE(RECORD_DATE) > DATE('2023-09-01');

// distribution of different client calls


SELECT
    CLIENT,
    COUNT(*) AS NUM_API_CALLS
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) >= DATE('2023-08-01')
    AND DATE(RECORD_DATE) < DATE('2023-09-01')
GROUP BY CLIENT
ORDER BY NUM_API_CALLS DESC;

SELECT
    USER_AGENT,
    COUNT(*) AS NUM_API_CALLS
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) >= DATE('2023-08-01')
    AND DATE(RECORD_DATE) < DATE('2023-09-01')
    AND CLIENT = 'UNKNOWN'
GROUP BY USER_AGENT
ORDER BY NUM_API_CALLS DESC;
// Distribution of normalized API calls this month
SELECT
    NORMALIZED_METHOD_SIGNATURE,
    COUNT(*) AS NUM_API_CALLS
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) >= DATE('2023-08-01')
    AND DATE(RECORD_DATE) < DATE('2023-09-01')
    AND CLIENT = 'PYTHON'
GROUP BY NORMALIZED_METHOD_SIGNATURE
ORDER BY NUM_API_CALLS DESC;

// Distribution of Python API calls this month
SELECT
    NORMALIZED_METHOD_SIGNATURE,
    COUNT(*) AS NUM_API_CALLS
FROM PROCESSEDACCESSRECORD
WHERE
    DATE(RECORD_DATE) > DATE('2023-09-01')
    AND CLIENT = 'PYTHON'
GROUP BY NORMALIZED_METHOD_SIGNATURE
ORDER BY NUM_API_CALLS DESC;


SELECT
    NORMALIZED_METHOD_SIGNATURE,
    COUNT(*) AS NUM_API_CALLS
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) >= DATE('2023-08-01')
    AND DATE(RECORD_DATE) < DATE('2023-09-01')
    AND CLIENT = 'SYNAPSER'
GROUP BY NORMALIZED_METHOD_SIGNATURE
ORDER BY NUM_API_CALLS DESC;

// Number of Python calls per user
WITH U AS (
    SELECT
        USER_ID,
        COUNT(*) AS USER_CALLS
    FROM PROCESSEDACCESS
    WHERE
        DATE(RECORD_DATE) > DATE('2023-09-01')
        AND CLIENT = 'PYTHON'
    GROUP BY USER_ID
),

T AS (
    SELECT DISTINCT
        ID,
        USER_NAME,
        EMAIL
    FROM USERPROFILE_LATEST
)

SELECT
    U.*,
    T.*
FROM U
LEFT JOIN T
    ON U.USER_ID = T.ID
ORDER BY U.USER_CALLS DESC;

// Number of client calls per month
SELECT
    CLIENT,
    MONTH(RECORD_DATE) AS MONTH_CALLED,
    COUNT(*) AS NUM_API_CALLS
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) >= DATE('2023-01-01')
GROUP BY CLIENT, MONTH(RECORD_DATE)
ORDER BY MONTH_CALLED ASC, NUM_API_CALLS DESC;

// User agents of user agents for clients that are unknown.
SELECT
    USER_AGENT,
    COUNT(*) AS USER_AGENT_COUNT
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) > DATE('2023-09-01') AND CLIENT = 'UNKNOWN'
GROUP BY USER_AGENT
ORDER BY USER_AGENT_COUNT DESC;

// User agents that are using the Python aiohttp package 
SELECT *
FROM PROCESSEDACCESS
WHERE
    USER_AGENT = 'Python/3.7 aiohttp/3.7.4.post0'
    AND DATE(RECORD_DATE) > DATE('2023-09-01');

// Different client versions for synapse R
SELECT DISTINCT USER_AGENT
FROM PROCESSEDACCESS
WHERE
    DATE(RECORD_DATE) > DATE('2023-09-01')
    AND CLIENT = 'SYNAPSER';
