USE DATABASE RECOVER;
USE SCHEMA PILOT_RAW;

// Records per table
SELECT
    TABLE_NAME,
    ROW_COUNT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PILOT_RAW';

DESC TABLE FITBITDAILYDATA;
CREATE SCHEMA PILOT WITH MANAGED ACCESS;
CREATE VIEW IF NOT EXISTS PILOT.TABLE_SUMMARY AS (
    WITH TABLE_COUNTS AS (
        SELECT
            'ENROLLEDPARTICIPANTS' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.ENROLLEDPARTICIPANTS
        UNION ALL
        SELECT
            'ENROLLEDPARTICIPANTS_CUSTOMFIELDS_SYMPTOMS' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.ENROLLEDPARTICIPANTS_CUSTOMFIELDS_SYMPTOMS
        UNION ALL
        SELECT
            'ENROLLEDPARTICIPANTS_CUSTOMFIELDS_TREATMENTS' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.ENROLLEDPARTICIPANTS_CUSTOMFIELDS_TREATMENTS
        UNION ALL
        SELECT
            'FITBITDAILYDATA' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.FITBITDAILYDATA
        UNION ALL
        SELECT
            'FITBITDEVICES' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.FITBITDEVICES
        UNION ALL
        SELECT
            'FITBITINTRADAYCOMBINED' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.FITBITINTRADAYCOMBINED
        UNION ALL
        SELECT
            'FITBITRESTINGHEARTRATES' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.FITBITRESTINGHEARTRATES
        UNION ALL
        SELECT
            'FITBITSLEEPLOGS' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.FITBITSLEEPLOGS
        UNION ALL
        SELECT
            'GARMINDAILYSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINDAILYSUMMARY
        UNION ALL
        SELECT
            'GARMINEPOCHSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINEPOCHSUMMARY
        UNION ALL
        SELECT
            'GARMINHRVSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINHRVSUMMARY
        UNION ALL
        SELECT
            'GARMINPULSEOXSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINPULSEOXSUMMARY
        UNION ALL
        SELECT
            'GARMINRESPIRATIONSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINRESPIRATIONSUMMARY
        UNION ALL
        SELECT
            'GARMINSLEEPSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINSLEEPSUMMARY
        UNION ALL
        SELECT
            'GARMINSTRESSDETAILSUMMARY' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GARMINSTRESSDETAILSUMMARY
        UNION ALL
        SELECT
            'GOOGLEFITSAMPLES' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.GOOGLEFITSAMPLES
        UNION ALL
        SELECT
            'HEALTHKITV2ACTIVITYSUMMARIES' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.HEALTHKITV2ACTIVITYSUMMARIES
        UNION ALL
        SELECT
            'HEALTHKITV2ELECTROCARDIOGRAM' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.HEALTHKITV2ELECTROCARDIOGRAM
        UNION ALL
        SELECT
            'HEALTHKITV2HEARTBEAT' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.HEALTHKITV2HEARTBEAT
        UNION ALL
        SELECT
            'HEALTHKITV2SAMPLES' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.HEALTHKITV2SAMPLES
        UNION ALL
        SELECT
            'HEALTHKITV2STATISTICS' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.HEALTHKITV2STATISTICS
        UNION ALL
        SELECT
            'HEALTHKITV2WORKOUTS' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.HEALTHKITV2WORKOUTS
        UNION ALL
        SELECT
            'SYMPTOMLOG' AS TABLE_NAME,
            COUNT(DISTINCT "ParticipantIdentifier") AS COUNT
        FROM RECOVER.PILOT_RAW.SYMPTOMLOG
    )

    SELECT
        TABLE_COUNTS.TABLE_NAME,
        TABLE_COUNTS.COUNT AS UNIQUE_NUMBER_OF_PARTICIPANTS,
        INFO.ROW_COUNT AS NUMBER_OF_RECORDS
    FROM TABLE_COUNTS
    LEFT JOIN INFORMATION_SCHEMA.TABLES AS INFO
        ON TABLE_COUNTS.TABLE_NAME = INFO.TABLE_NAME
);

SELECT * FROM PILOT.TABLE_SUMMARY;
