USE ROLE SYSADMIN;
USE DATABASE SYNAPSE_DATA_WAREHOUSE;
USE SCHEMA SYNAPSE;

// GENIE
SELECT
    GENIE."id",
    GENIE."name",
    GENIE."version",
    count(*) AS NUMBER_OF_DOWNLOADS
FROM SAGE.PORTAL_RAW.GENIE AS GENIE
LEFT JOIN
    SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW.FILEDOWNLOAD AS FD
    ON
        GENIE."dataFileHandleId" = FD.FILE_HANDLE_ID
GROUP BY
    GENIE."id", GENIE."name", GENIE."version"
ORDER BY
    NUMBER_OF_DOWNLOADS DESC;

// Download counts for AD files
SELECT
    AD."id",
    AD."name",
    AD."study",
    count(*) AS NUMBER_OF_DOWNLOADS
FROM SAGE.PORTAL_RAW.AD
LEFT JOIN
    SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW.FILEDOWNLOAD AS FD
    ON
        AD."dataFileHandleId" = FD.FILE_HANDLE_ID
GROUP BY
    AD."id", AD."name", AD."study"
ORDER BY
    NUMBER_OF_DOWNLOADS DESC;
