repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.3.4
  hooks:
    - id: sqlfluff-lint
      args: [--dialect, "snowflake"]
    - id: sqlfluff-fix
      # Arbitrary arguments to show an example
      args: [--dialect, "snowflake"]
      # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']