repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev:  3.0.6
  hooks:
    - id: sqlfluff-lint
      args: [--dialect, "snowflake", '--exclude-rules', 'RF05,AM04,LT05,ST07']
      exclude: ^transform/target/
    - id: sqlfluff-fix
      args: [--dialect, "snowflake", '--exclude-rules', 'RF05,AM04,LT05,ST07']
      exclude: ^transform/target/
      # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']