
USE DATABASE {{ database_name }};
USE ROLE {{ database_name }}_ADMIN;

-- ============================================================
-- SYNAPSE schema
-- ============================================================

CREATE OR ALTER DATABASE ROLE SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_ALL_ADMIN
TO ROLE {{ database_name }}_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_ALL_ADMIN
TO ROLE {{ database_name }}_ADMIN;

-- Object-type-specific read roles (owned by admin, granted to analyst aggregate)
CREATE OR ALTER DATABASE ROLE SYNAPSE_TABLE_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_STAGE_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_VIEW_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_TASK_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_FUNCTION_READ;

GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_TABLE_READ
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_STAGE_READ
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_VIEW_READ
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_TASK_READ
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_FUNCTION_READ
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;

-- Analyst aggregate role: read-only access to all SYNAPSE objects
CREATE OR ALTER DATABASE ROLE SYNAPSE_ALL_ANALYST;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_ALL_ANALYST
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_ALL_ANALYST
TO ROLE {{ database_name }}_ANALYST;

GRANT DATABASE ROLE SYNAPSE_TABLE_READ    TO DATABASE ROLE SYNAPSE_ALL_ANALYST;
GRANT DATABASE ROLE SYNAPSE_STAGE_READ    TO DATABASE ROLE SYNAPSE_ALL_ANALYST;
GRANT DATABASE ROLE SYNAPSE_VIEW_READ     TO DATABASE ROLE SYNAPSE_ALL_ANALYST;
GRANT DATABASE ROLE SYNAPSE_TASK_READ     TO DATABASE ROLE SYNAPSE_ALL_ANALYST;
GRANT DATABASE ROLE SYNAPSE_FUNCTION_READ TO DATABASE ROLE SYNAPSE_ALL_ANALYST;

-- Developer aggregate role: inherits analyst + write-capable via account role
CREATE OR ALTER DATABASE ROLE SYNAPSE_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_ALL_DEVELOPER
TO DATABASE ROLE SYNAPSE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_ALL_DEVELOPER
TO ROLE DATA_ENGINEER;

GRANT DATABASE ROLE SYNAPSE_ALL_ANALYST   TO DATABASE ROLE SYNAPSE_ALL_DEVELOPER;
GRANT DATABASE ROLE SYNAPSE_FUNCTION_READ TO DATABASE ROLE SYNAPSE_ALL_DEVELOPER;

-- ============================================================
-- SYNAPSE_RAW schema
-- ============================================================

CREATE OR ALTER DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN
TO ROLE {{ database_name }}_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN
TO ROLE {{ database_name }}_ADMIN;

CREATE OR ALTER DATABASE ROLE SYNAPSE_RAW_TABLE_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_RAW_STAGE_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_RAW_STREAM_READ;
CREATE OR ALTER DATABASE ROLE SYNAPSE_RAW_TASK_READ;

GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_RAW_TABLE_READ
TO DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_RAW_STAGE_READ
TO DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_RAW_STREAM_READ
TO DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_RAW_TASK_READ
TO DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN COPY CURRENT GRANTS;

-- Developer aggregate role (no analyst equivalent; raw schema is developer-only)
CREATE OR ALTER DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER
TO DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER
TO ROLE DATA_ENGINEER;

GRANT DATABASE ROLE SYNAPSE_RAW_TABLE_READ  TO DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;
GRANT DATABASE ROLE SYNAPSE_RAW_STAGE_READ  TO DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;
GRANT DATABASE ROLE SYNAPSE_RAW_STREAM_READ TO DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;
GRANT DATABASE ROLE SYNAPSE_RAW_TASK_READ   TO DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;

-- ============================================================
-- SCHEMACHANGE schema
-- ============================================================

CREATE OR ALTER DATABASE ROLE SCHEMACHANGE_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE SCHEMACHANGE_ALL_ADMIN
TO ROLE {{ database_name }}_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SCHEMACHANGE_ALL_ADMIN
TO ROLE {{ database_name }}_ADMIN;

CREATE OR ALTER DATABASE ROLE SCHEMACHANGE_TABLE_READ;
GRANT OWNERSHIP ON DATABASE ROLE SCHEMACHANGE_TABLE_READ
TO DATABASE ROLE SCHEMACHANGE_ALL_ADMIN COPY CURRENT GRANTS;

CREATE OR ALTER DATABASE ROLE SCHEMACHANGE_ALL_ANALYST;
GRANT OWNERSHIP ON DATABASE ROLE SCHEMACHANGE_ALL_ANALYST
TO DATABASE ROLE SCHEMACHANGE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SCHEMACHANGE_ALL_ANALYST
TO ROLE {{ database_name }}_ANALYST;
GRANT DATABASE ROLE SCHEMACHANGE_TABLE_READ TO DATABASE ROLE SCHEMACHANGE_ALL_ANALYST;

CREATE OR ALTER DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER
TO DATABASE ROLE SCHEMACHANGE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER
TO ROLE DATA_ENGINEER;
GRANT DATABASE ROLE SCHEMACHANGE_ALL_ANALYST TO DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER;

-- ============================================================
-- SYNAPSE_AGGREGATE schema
-- Owned by the proxy admin account role (not the database admin)
-- to allow serverless dynamic table refresh
-- ============================================================

USE ROLE {{ database_name }}_PROXY_ADMIN;

CREATE OR ALTER DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN;

CREATE OR ALTER DATABASE ROLE SYNAPSE_AGGREGATE_TABLE_READ;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_AGGREGATE_TABLE_READ
TO DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ADMIN COPY CURRENT GRANTS;

CREATE OR ALTER DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ANALYST;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ANALYST
TO DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_AGGREGATE_TABLE_READ TO DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ANALYST;

CREATE OR ALTER DATABASE ROLE SYNAPSE_AGGREGATE_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_AGGREGATE_ALL_DEVELOPER
TO DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_AGGREGATE_ALL_ANALYST TO DATABASE ROLE SYNAPSE_AGGREGATE_ALL_DEVELOPER;

-- ============================================================
-- SYNAPSE_EVENT schema
-- Owned by the proxy admin account role (same reason as aggregate)
-- ============================================================

CREATE OR ALTER DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN;

CREATE OR ALTER DATABASE ROLE SYNAPSE_EVENT_TABLE_READ;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_EVENT_TABLE_READ
TO DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN COPY CURRENT GRANTS;

CREATE OR ALTER DATABASE ROLE SYNAPSE_EVENT_ALL_ANALYST;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_EVENT_ALL_ANALYST
TO DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_EVENT_TABLE_READ TO DATABASE ROLE SYNAPSE_EVENT_ALL_ANALYST;

CREATE OR ALTER DATABASE ROLE SYNAPSE_EVENT_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_EVENT_ALL_DEVELOPER
TO DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE SYNAPSE_EVENT_ALL_ANALYST TO DATABASE ROLE SYNAPSE_EVENT_ALL_DEVELOPER;

-- Restricted read role for governance users (provides USAGE on SYNAPSE_EVENT schema only)
CREATE OR ALTER DATABASE ROLE SYNAPSE_EVENT_GOVERNANCE_READ;
GRANT OWNERSHIP ON DATABASE ROLE SYNAPSE_EVENT_GOVERNANCE_READ
TO DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN COPY CURRENT GRANTS;
GRANT USAGE ON SCHEMA SYNAPSE_EVENT TO DATABASE ROLE SYNAPSE_EVENT_GOVERNANCE_READ;

-- ============================================================
-- RDS_LANDING schema
-- ============================================================

CREATE OR ALTER DATABASE ROLE RDS_LANDING_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE RDS_LANDING_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE RDS_LANDING_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN;

CREATE OR ALTER DATABASE ROLE RDS_LANDING_TABLE_READ;
CREATE OR ALTER DATABASE ROLE RDS_LANDING_STAGE_READ;
GRANT OWNERSHIP ON DATABASE ROLE RDS_LANDING_TABLE_READ
TO DATABASE ROLE RDS_LANDING_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE RDS_LANDING_STAGE_READ
TO DATABASE ROLE RDS_LANDING_ALL_ADMIN COPY CURRENT GRANTS;

CREATE OR ALTER DATABASE ROLE RDS_LANDING_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE RDS_LANDING_ALL_DEVELOPER
TO DATABASE ROLE RDS_LANDING_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE RDS_LANDING_ALL_DEVELOPER
TO ROLE DATA_ENGINEER;
GRANT DATABASE ROLE RDS_LANDING_TABLE_READ TO DATABASE ROLE RDS_LANDING_ALL_DEVELOPER;
GRANT DATABASE ROLE RDS_LANDING_STAGE_READ TO DATABASE ROLE RDS_LANDING_ALL_DEVELOPER;

-- ============================================================
-- RDS_RAW schema
-- ============================================================

CREATE OR ALTER DATABASE ROLE RDS_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON DATABASE ROLE RDS_RAW_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE RDS_RAW_ALL_ADMIN
TO ROLE {{ database_name }}_PROXY_ADMIN;

CREATE OR ALTER DATABASE ROLE RDS_RAW_TABLE_READ;
CREATE OR ALTER DATABASE ROLE RDS_RAW_VIEW_READ;
GRANT OWNERSHIP ON DATABASE ROLE RDS_RAW_TABLE_READ
TO DATABASE ROLE RDS_RAW_ALL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON DATABASE ROLE RDS_RAW_VIEW_READ
TO DATABASE ROLE RDS_RAW_ALL_ADMIN COPY CURRENT GRANTS;

CREATE OR ALTER DATABASE ROLE RDS_RAW_ALL_DEVELOPER;
GRANT OWNERSHIP ON DATABASE ROLE RDS_RAW_ALL_DEVELOPER
TO DATABASE ROLE RDS_RAW_ALL_ADMIN COPY CURRENT GRANTS;
GRANT DATABASE ROLE RDS_RAW_ALL_DEVELOPER
TO ROLE DATA_ENGINEER;
GRANT DATABASE ROLE RDS_RAW_TABLE_READ TO DATABASE ROLE RDS_RAW_ALL_DEVELOPER;
GRANT DATABASE ROLE RDS_RAW_VIEW_READ  TO DATABASE ROLE RDS_RAW_ALL_DEVELOPER;
