USE ROLE ACCOUNTADMIN;
USE SCHEMA {{ database_name }}.SYNAPSE_RAW;

-- Streams on snapshot tables; final state accounts for V2.2.0 which recreated
-- CERTIFIEDQUIZ_STREAM and CERTIFIEDQUIZQUESTION_STREAM on the renamed *SNAPSHOTS tables.
CREATE STREAM IF NOT EXISTS ACLSNAPSHOTS_STREAM                     ON TABLE ACLSNAPSHOTS;
CREATE STREAM IF NOT EXISTS CERTIFIEDQUIZ_STREAM                    ON TABLE CERTIFIEDQUIZSNAPSHOTS;
CREATE STREAM IF NOT EXISTS CERTIFIEDQUIZQUESTION_STREAM            ON TABLE CERTIFIEDQUIZQUESTIONSNAPSHOTS;
CREATE STREAM IF NOT EXISTS USERPROFILESNAPSHOT_STREAM              ON TABLE USERPROFILESNAPSHOT;
CREATE STREAM IF NOT EXISTS TEAMMEMBERSNAPSHOTS_STREAM              ON TABLE TEAMMEMBERSNAPSHOTS;
CREATE STREAM IF NOT EXISTS FILESNAPSHOTS_STREAM                    ON TABLE FILESNAPSHOTS;
CREATE STREAM IF NOT EXISTS NODESNAPSHOTS_STREAM                    ON TABLE NODESNAPSHOTS;
CREATE STREAM IF NOT EXISTS TEAMSNAPSHOTS_STREAM                    ON TABLE TEAMSNAPSHOTS;
CREATE STREAM IF NOT EXISTS USERGROUPSNAPSHOTS_STREAM               ON TABLE USERGROUPSNAPSHOTS;
CREATE STREAM IF NOT EXISTS VERIFICATIONSUBMISSIONSNAPSHOTS_STREAM  ON TABLE VERIFICATIONSUBMISSIONSNAPSHOTS;
