USE ROLE sysadmin;
USE DATABASE sage;

CREATE SCHEMA IF NOT EXISTS portal_raw
WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS portal_downloads
WITH MANAGED ACCESS;
CREATE SCHEMA IF NOT EXISTS audit
WITH MANAGED ACCESS;

CREATE SCHEMA IF NOT EXISTS ad
WITH MANAGED ACCESS;
