USE DATABASE {{ database_name }}; --noqa: JJ01,PRS,TMP

-- Snowflake will not let us disable managed access without revoking
-- preexisting future grants on the schema.
REVOKE SELECT 
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    FROM ROLE AD;
REVOKE SELECT 
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    FROM ROLE DATA_ANALYTICS;
REVOKE SELECT 
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    FROM ROLE DATA_ANALYTICS;
REVOKE SELECT 
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    FROM ROLE PUBLIC;

ALTER SCHEMA SYNAPSE
    DISABLE MANAGED ACCESS;

-- Reapply future grants to keep everything the same
GRANT SELECT 
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO ROLE AD;
GRANT SELECT 
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO ROLE DATA_ANALYTICS;
GRANT SELECT 
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO ROLE DATA_ANALYTICS;
GRANT SELECT 
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO ROLE PUBLIC;