USE SCHEMA {{database_name}}.synapse;  --noqa: JJ01,PRS,TMP

ALTER DYNAMIC TABLE ACCESSREQUIREMENT_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE ACL_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE CERTIFIEDQUIZQUESTION_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE FILEHANDLEASSOCIATION_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE FILE_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE NODE_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE PROJECTSETTING_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE TEAMMEMBER_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE TEAM_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE USERGROUP_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE USERPROFILE_LATEST
SET WAREHOUSE = dpe_automation;
ALTER DYNAMIC TABLE VERIFICATIONSUBMISSION_LATEST
SET WAREHOUSE = dpe_automation;
