USE ROLE SYSADMIN;
USE DATABASE SAGE;

CREATE OR ALTER SCHEMA AUDIT WITH MANAGED ACCESS;
CREATE OR ALTER SCHEMA AD WITH MANAGED ACCESS;
CREATE OR ALTER SCHEMA CITATIONS;
CREATE OR ALTER SCHEMA GOVERNANCE;
CREATE OR ALTER SCHEMA GOOGLE_ANALYTICS_AGGREGATE;
