GRANT OWNERSHIP
	ON ALL FUNCTIONS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL FUNCTIONS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN
	COPY CURRENT GRANTS;