-- Transfer ownership of BACKUP_SYNAPSE_DATA_WAREHOUSE task (our only task)
-- to the usual task owner.
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN
	COPY CURRENT GRANTS;