-- Transfer ownership of all tables in `SAGE.CITATIONS`,
-- as well as ownership of the schema itself.
GRANT OWNERSHIP
ON TABLE SAGE.CITATIONS.AD_GOOGLE_SCHOLAR
TO ROLE SAGE_CITATIONS_ADMIN
REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
ON TABLE SAGE.CITATIONS.GENIE
TO ROLE SAGE_CITATIONS_ADMIN
REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
ON TABLE SAGE.CITATIONS.GENIE_GOOGLE_SCHOLAR
TO ROLE SAGE_CITATIONS_ADMIN
REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
ON TABLE SAGE.CITATIONS.SYNAPSE_MINTED_DOIS
TO ROLE SAGE_CITATIONS_ADMIN
REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
ON SCHEMA SAGE.CITATIONS
TO ROLE SAGE_CITATIONS_ADMIN
REVOKE CURRENT GRANTS;
