-- SYNAPSE_DATA_WAREHOUSE
GRANT OWNERSHIP
    ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_ADMIN
    REVOKE CURRENT GRANTS;
-- Grant ownership on initial "test" table
GRANT OWNERSHIP
    ON ALL TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_ADMIN
    REVOKE CURRENT GRANTS;

-- SYNAPSE_DATA_WAREHOUSE_DEV
GRANT OWNERSHIP
    ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_ADMIN
    REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
    ON ALL TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_ADMIN
    REVOKE CURRENT GRANTS;