-- Grant ownership of internamespace objects
-- **in** SYNAPSE_EVENT schema
-- **to** <DOMAIN>.ALL_ADMIN database role.
-- Which is owned by <DOMAIN>_PROXY_ADMIN account role, thus making it owned by PROXY_ADMIN role.

-- PROD
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.ALL_ADMIN
	COPY CURRENT GRANTS;

-- DEV
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.ALL_ADMIN
	COPY CURRENT GRANTS;
