--Need to transfer ownership of GENIE db's schemas, tables and 
--other objects to GENIE_ADMIN
GRANT OWNERSHIP
ON DATABASE GENIE
TO ROLE GENIE_ADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON ALL SCHEMAS
IN DATABASE GENIE
TO ROLE GENIE_ADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON ALL TABLES
IN DATABASE GENIE
TO ROLE GENIE_ADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON ALL VIEWS
IN DATABASE GENIE
TO ROLE GENIE_ADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON ALL STAGES
IN DATABASE GENIE
TO ROLE GENIE_ADMIN
COPY CURRENT GRANTS;

GRANT OWNERSHIP
ON ALL FILE FORMATS
IN DATABASE GENIE
TO ROLE GENIE_ADMIN
COPY CURRENT GRANTS;
