-- ACCOUNTADMIN currently owns GOOGLE_ANALYTICS_AGGREGATE schema because it was
-- created as part of the GOOGLE_ANALYTICS application setup.
GRANT OWNERSHIP
    ON SCHEMA SAGE.GOOGLE_ANALYTICS_AGGREGATE
    TO ROLE GOOGLE_ANALYTICS_AGGREGATE_ADMIN
    COPY CURRENT GRANTS;