-- Transfer ownership of RDS_RAW PII masking policies to RDS_RAW_ALL_ADMIN.

GRANT OWNERSHIP
    ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_TEXT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN
    REVOKE CURRENT GRANTS;

GRANT OWNERSHIP
    ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_BINARY
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN
    REVOKE CURRENT GRANTS;

GRANT OWNERSHIP
    ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_TEXT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN
    REVOKE CURRENT GRANTS;

GRANT OWNERSHIP
    ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_BINARY
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN
    REVOKE CURRENT GRANTS;
