---- RBAC reconfiguration of data warehouse ----
-- The following grants transfer ownership of current and future 
-- data warehouse objects from SYSADMIN to each namespace's respective
-- `*ALL_ADMIN` database role.

---- SYNAPSE_DATA_WAREHOUSE_DEV ----
GRANT OWNERSHIP
    ON DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN
	COPY CURRENT GRANTS;

-- SYNAPSE
GRANT OWNERSHIP
	ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN
	COPY CURRENT GRANTS;
-- GRANT OWNERSHIP
-- 	ON ALL DYNAMIC TABLES
-- 	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
-- 	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN
-- 	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO ROLE SYSADMIN
	COPY CURRENT GRANTS;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL STAGES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL STREAMS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN
	COPY CURRENT GRANTS;
-- GRANT OWNERSHIP
-- 	ON ALL TASKS
-- 	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
-- 	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN
-- 	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO ROLE SYSADMIN
	COPY CURRENT GRANTS;

-- SCHEMACHANGE
GRANT OWNERSHIP
	ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ADMIN
	COPY CURRENT GRANTS;