-- Transfer ownership of the SAGE.AUDIT schema to SAGE_AUDIT_ADMIN
GRANT OWNERSHIP
    ON SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ADMIN
    REVOKE CURRENT GRANTS;

GRANT OWNERSHIP
    ON ALL TABLES IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ADMIN
    REVOKE CURRENT GRANTS;

GRANT OWNERSHIP
    ON ALL VIEWS IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ADMIN
    REVOKE CURRENT GRANTS;

GRANT OWNERSHIP
    ON ALL GIT REPOSITORIES IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ADMIN
    REVOKE CURRENT GRANTS;
