-- Transfer ownership of the SAGE.AD schema to SAGE_AD_ADMIN.
GRANT OWNERSHIP
    ON SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;

-- Transfer ownership of existing objects in SAGE.AD to SAGE_AD_ADMIN.
GRANT OWNERSHIP
    ON ALL TABLES IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
    ON ALL VIEWS IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
    ON ALL STAGES IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
    ON ALL FILE FORMATS IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
    ON ALL FUNCTIONS IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;
GRANT OWNERSHIP
    ON ALL PROCEDURES IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN
    REVOKE CURRENT GRANTS;
