-- Grant ownership of internamespace objects to proxy admin database role
-- SYNAPSE
GRANT OWNERSHIP
	ON ALL DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.ALL_ADMIN
	COPY CURRENT GRANTS;
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.ALL_ADMIN
	COPY CURRENT GRANTS;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.ALL_ADMIN
	COPY CURRENT GRANTS;