-- Transfer ownership of the `*ALL_ADMIN` database roles from the
-- proxy admin database role to the dev database admin
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN
    COPY CURRENT GRANTS;
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN
    COPY CURRENT GRANTS;
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ADMIN
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN
    COPY CURRENT GRANTS;