-- Transfer ownership of the `*ALL_ADMIN` database roles from the
-- proxy admin database role to the prod database admin
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN
    TO ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN
    COPY CURRENT GRANTS;
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN
    TO ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN
    COPY CURRENT GRANTS;
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_ALL_ADMIN
    TO ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN
    COPY CURRENT GRANTS;