-- Grant ownership of internamespace objects to proxy admin role
-- SYNAPSE
GRANT OWNERSHIP
	ON ALL DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ALL_ADMIN
	COPY CURRENT GRANTS;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON ALL TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ALL_ADMIN
	COPY CURRENT GRANTS;