USE DATABASE {{ database_name }}; --noqa: JJ01,PRS,TMP

-- Create roles which will inherit the respective *ALL_ANALYST database role
CREATE OR REPLACE DATABASE ROLE SYNAPSE_ALL_DEVELOPER;
CREATE OR REPLACE DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;
CREATE OR REPLACE DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER;

-- Grant ownership of each developer role to its 
-- respective admin role
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_ALL_DEVELOPER
    TO DATABASE ROLE SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER
    TO DATABASE ROLE SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
    ON DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER
    TO DATABASE ROLE SCHEMACHANGE_ALL_ADMIN;

-- Grant each *ALL_ANALYST role to its respective *ALL_DEVELOPER role
GRANT USAGE
    ON DATABASE ROLE SYNAPSE_ALL_ANALYST
    TO DATABASE ROLE SYNAPSE_ALL_DEVELOPER;
GRANT USAGE
    ON DATABASE ROLE SYNAPSE_RAW_ALL_ANALYST
    TO DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER;
GRANT USAGE
    ON DATABASE ROLE SCHEMACHANGE_ALL_ANALYST
    TO DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER;

-- Grant developer database roles to the developer account role
GRANT DATABASE ROLE SYNAPSE_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;
GRANT DATABASE ROLE SYNAPSE_RAW_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;
GRANT DATABASE ROLE SCHEMACHANGE_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;
