USE DATABASE {{ database_name }}; --noqa: JJ01,PRS,TMP

-- Create function read roles, grant ownership to admin and
-- usage to analyst and developer
CREATE OR REPLACE DATABASE ROLE SYNAPSE_FUNCTION_READ;
GRANT OWNERSHIP
	ON DATABASE ROLE SYNAPSE_FUNCTION_READ
	TO DATABASE ROLE SYNAPSE_ALL_ADMIN;
GRANT DATABASE ROLE SYNAPSE_FUNCTION_READ
	TO DATABASE ROLE SYNAPSE_ALL_ANALYST;
GRANT DATABASE ROLE SYNAPSE_FUNCTION_READ
	TO DATABASE ROLE SYNAPSE_ALL_DEVELOPER;
