USE DATABASE {{ database_name }}; --noqa: JJ01,PRS,TMP

-- Create a database role for governance read access to SYNAPSE_EVENT schema objects
CREATE OR REPLACE DATABASE ROLE SYNAPSE_EVENT_GOVERNANCE_READ;

-- Grant ownership to the SYNAPSE_EVENT admin role
GRANT OWNERSHIP
    ON DATABASE ROLE SYNAPSE_EVENT_GOVERNANCE_READ
    TO DATABASE ROLE SYNAPSE_EVENT_ALL_ADMIN;

-- Grant USAGE on the SYNAPSE_EVENT schema
GRANT USAGE
    ON SCHEMA SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_EVENT_GOVERNANCE_READ;
