USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS SAGE;
CREATE DATABASE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE;
CREATE DATABASE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV;
CREATE DATABASE IF NOT EXISTS RECOVER;
CREATE DATABASE IF NOT EXISTS METADATA;
