USE WAREHOUSE COMPUTE_ORG;
USE ROLE SECURITYADMIN;

// Grant system roles to users
GRANT ROLE SYSADMIN
TO USER "kevin.boske@sagebase.org";

GRANT ROLE SYSADMIN
TO USER "x.schildwachter@sagebase.org";

// GENIE
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS GENIE_ADMIN;
USE ROLE SECURITYADMIN;
GRANT ROLE GENIE_ADMIN
TO ROLE USERADMIN;
GRANT ROLE GENIE_ADMIN
TO USER "alex.paynter@sagebase.org";
GRANT ROLE GENIE_ADMIN
TO USER "xindi.guo@sagebase.org";
GRANT ROLE GENIE_ADMIN
TO USER "chelsea.nayan@sagebase.org";

// RECOVER
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS RECOVER_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS RECOVER_DATA_ANALYTICS;

USE ROLE SECURITYADMIN;
GRANT ROLE RECOVER_DATA_ENGINEER
TO ROLE USERADMIN;
GRANT ROLE RECOVER_DATA_ANALYTICS
TO ROLE USERADMIN;
GRANT ROLE RECOVER_DATA_ENGINEER
TO USER "phil.snyder@sagebase.org";
GRANT ROLE RECOVER_DATA_ENGINEER
TO USER "rixing.xu@sagebase.org";
GRANT ROLE RECOVER_DATA_ENGINEER
TO USER "thomas.yu@sagebase.org";

// AD
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS AD;
USE ROLE SECURITYADMIN;
GRANT ROLE AD
TO ROLE USERADMIN;
GRANT ROLE AD
TO USER "abby.vanderlinden@sagebase.org";

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS MASKING_ADMIN;
GRANT ROLE MASKING_ADMIN
TO USER "thomas.yu@sagebase.org";
USE ROLE ACCOUNTADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT
TO ROLE MASKING_ADMIN;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
USE ROLE SECURITYADMIN;
GRANT ROLE DATA_ENGINEER
TO ROLE USERADMIN;

GRANT ROLE DATA_ENGINEER
TO USER "phil.snyder@sagebase.org";
GRANT ROLE DATA_ENGINEER
TO USER "rixing.xu@sagebase.org";
GRANT ROLE DATA_ENGINEER
TO USER "thomas.yu@sagebase.org";
GRANT ROLE DATA_ENGINEER
TO USER "brad.macdonald@sagebase.org";
GRANT ROLE DATA_ENGINEER
TO USER "bryan.fauble@sagebase.org";
