USE ROLE USERADMIN;

-- TODO: Create role for tableau warehouse
-- system wide roles
CREATE ROLE IF NOT EXISTS MASKING_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYTICS;

-- DPE ops
CREATE ROLE IF NOT EXISTS DPE_OPS;

-- GENIE roles
CREATE ROLE IF NOT EXISTS GENIE_ADMIN;

-- RECOVER roles
CREATE ROLE IF NOT EXISTS RECOVER_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS RECOVER_DATA_ANALYTICS;

-- AD
CREATE ROLE IF NOT EXISTS AD;

-- FAIR
CREATE ROLE IF NOT EXISTS FAIR;
-- GOVERNANCE
CREATE ROLE IF NOT EXISTS GOVERNANCE;
CREATE ROLE IF NOT EXISTS TASKADMIN;
CREATE ROLE IF NOT EXISTS SAGE_LEADERS;

-- NF
CREATE ROLE IF NOT EXISTS NF_ADMIN;

-- SCIDATA
CREATE ROLE IF NOT EXISTS SCIDATA_ADMIN;

-- SYNAPSE_DATA_WAREHOUSE domain roles
CREATE ROLE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_ADMIN;
CREATE ROLE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_ANALYST;

-- SYNAPSE_DATA_WAREHOUSE_DEV domain roles
CREATE ROLE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN;
CREATE ROLE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV_ANALYST;

-- Data Warehouse proxy admin roles
CREATE ROLE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_ALL_ADMIN;
CREATE ROLE IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV_ALL_ADMIN;

-- Rename previous roles to make them less confusing
ALTER ROLE SYNAPSE_DATA_WAREHOUSE_ALL_ADMIN
    RENAME TO SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
ALTER ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ALL_ADMIN
    RENAME TO SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;