USE ROLE USERADMIN;

-- TODO: Create role for tableau warehouse
-- system wide roles
CREATE ROLE IF NOT EXISTS MASKING_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYTICS;

-- DPE ops
CREATE ROLE IF NOT EXISTS DPE_OPS;

-- GENIE roles
CREATE ROLE IF NOT EXISTS GENIE_ADMIN;

-- RECOVER roles
CREATE ROLE IF NOT EXISTS RECOVER_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS RECOVER_DATA_ANALYTICS;

-- AD
CREATE ROLE IF NOT EXISTS AD;

-- FAIR
CREATE ROLE IF NOT EXISTS FAIR;
-- GOVERNANCE
CREATE ROLE IF NOT EXISTS GOVERNANCE;
CREATE ROLE IF NOT EXISTS TASKADMIN;
CREATE ROLE IF NOT EXISTS SAGE_LEADERS;
