USE ROLE sysadmin;
USE DATABASE sage;

CREATE SCHEMA IF NOT EXISTS portal_raw
WITH MANAGED ACCESS;

CREATE SCHEMA IF NOT EXISTS portal_downloads
WITH MANAGED ACCESS;
-- ! One time addition
-- ALTER TABLE portal_raw.NF ADD COLUMN "tissue" STRING;

USE ROLE securityadmin;

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE sage
TO ROLE public;
GRANT SELECT ON FUTURE TABLES IN DATABASE sage
TO ROLE public;
GRANT USAGE ON DATABASE sage
TO ROLE public;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE sage
TO ROLE data_engineer;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE sage
TO ROLE data_engineer;
GRANT CREATE SCHEMA, USAGE ON DATABASE sage
TO ROLE data_engineer;

-- GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SAGE
-- TO ROLE data_engineer;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SAGE
-- TO ROLE data_engineer;

CREATE SCHEMA IF NOT EXISTS ad
WITH MANAGED ACCESS;

USE ROLE securityadmin;
GRANT ALL PRIVILEGES ON SCHEMA ad
TO ROLE ad;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ad
TO ROLE sysadmin;
GRANT USAGE ON DATABASE sage
TO ROLE ad;
