USE ROLE sysadmin;
USE DATABASE sage;

CREATE SCHEMA IF NOT EXISTS portal_raw
    WITH MANAGED ACCESS;
-- ! One time addition
-- ALTER TABLE portal_raw.NF ADD COLUMN "tissue" STRING;

USE ROLE securityadmin;

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE sage
TO ROLE PUBLIC;
GRANT SELECT ON FUTURE TABLES IN DATABASE sage
TO ROLE PUBLIC;
GRANT USAGE ON DATABASE sage
TO ROLE PUBLIC;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE SAGE
TO ROLE data_engineer;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SAGE
TO ROLE data_engineer;
GRANT CREATE SCHEMA, USAGE ON DATABASE SAGE
TO ROLE data_engineer;

-- GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SAGE
-- TO ROLE data_engineer;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SAGE
-- TO ROLE data_engineer;

CREATE SCHEMA IF NOT EXISTS AD
    WITH MANAGED ACCESS;

USE ROLE securityadmin;
GRANT ALL PRIVILEGES ON SCHEMA AD
TO ROLE AD;
grant ALL PRIVILEGES ON FUTURE TABLES in schema AD
TO ROLE sysadmin;
GRANT USAGE ON DATABASE sage
TO ROLE AD;
