// https://docs.snowflake.com/en/user-guide/oauth-partner
USE ROLE ACCOUNTADMIN;
CREATE SECURITY INTEGRATION IF NOT EXISTS ts_oauth_int2
  TYPE = OAUTH
  ENABLED = TRUE
  OAUTH_CLIENT = TABLEAU_SERVER
  OAUTH_REFRESH_TOKEN_VALIDITY = 86400;
  -- BLOCKED_ROLES_LIST = ('SYSADMIN');

CREATE SECURITY INTEGRATION IF NOT EXISTS td_oauth_int2
  TYPE = OAUTH
  ENABLED = TRUE
  OAUTH_REFRESH_TOKEN_VALIDITY = 36000
  -- BLOCKED_ROLES_LIST = ('SYSADMIN');
  OAUTH_CLIENT = TABLEAU_DESKTOP;

DESC SECURITY INTEGRATION ts_oauth_int2;
