use role sysadmin;
create warehouse recover_xsmall
 WAREHOUSE_TYPE = STANDARD
 WAREHOUSE_SIZE = XSMALL
 AUTO_SUSPEND = 300
 AUTO_RESUME = TRUE
 INITIALLY_SUSPENDED = TRUE;

create warehouse tableau
 WAREHOUSE_TYPE = STANDARD
 WAREHOUSE_SIZE = XSMALL
 AUTO_SUSPEND = 300
 AUTO_RESUME = TRUE
 INITIALLY_SUSPENDED = TRUE;

USE ROLE securityadmin;
GRANT USAGE ON WAREHOUSE tableau TO ROLE genie_admin;