USE SCHEMA POLICY_DB.PUBLIC;

-- Add the new authentication method to the existing policy
ALTER AUTHENTICATION POLICY USER_AUTHENTICATION_POLICY
    SET AUTHENTICATION_METHODS = ('SAML', 'KEYPAIR', 'PROGRAMMATIC_ACCESS_TOKEN');

-- Set the expiration to 30 days
ALTER AUTHENTICATION POLICY USER_AUTHENTICATION_POLICY
    SET PAT_POLICY = (DEFAULT_EXPIRY_IN_DAYS=90);

