USE SCHEMA POLICY_DB.PUBLIC;

-- 1. Update the authentication policy with all desired methods
ALTER AUTHENTICATION POLICY ADMIN_AUTHENTICATION_POLICY
    SET AUTHENTICATION_METHODS = (
        'SAML',
        'KEYPAIR',
        'PROGRAMMATIC_ACCESS_TOKEN'
    );

-- 2. Set the PAT policy to be user-friendly
ALTER AUTHENTICATION POLICY ADMIN_AUTHENTICATION_POLICY
    SET PAT_POLICY = (
        DEFAULT_EXPIRY_IN_DAYS = 365,
        NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED
    );
