-- PII masking policies for the RDS_RAW schema
--
-- The real value is returned only when the querying
-- session holds the database role RDS_RAW_TABLE_READ (the uncensored read role);
-- otherwise all values are returned as NULL.

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_TEXT
    AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_BINARY
    AS (val BINARY) RETURNS BINARY ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_TEXT
    AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_BINARY
    AS (val BINARY) RETURNS BINARY ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;
