-- PII masking policies for the RDS_RAW schema, modeled on the ad hoc pattern in
-- root apply_pii_masking.py: the real value is returned only when the querying
-- session holds RDS_RAW_TABLE_READ (the existing full/uncensored read role);
-- every other database role (including RDS_RAW_TABLE_READ_MASKED) sees NULL.
--
-- No columns are attached to these policies yet: none of the sensitive tables
-- (CREDENTIAL, OAUTH_*, OTP_*, PERSONAL_ACCESS_TOKEN, etc.) exist in RDS_RAW as
-- of this writing. Attachment happens in a follow-up migration once those
-- tables are added to RDS_RAW.

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_TEXT
    AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_BINARY
    AS (val BINARY) RETURNS BINARY ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_TEXT
    AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

CREATE MASKING POLICY IF NOT EXISTS SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_BINARY
    AS (val BINARY) RETURNS BINARY ->
    CASE
        WHEN IS_DATABASE_ROLE_IN_SESSION('RDS_RAW_TABLE_READ') THEN val
        ELSE NULL
    END;

-- Let RDS_RAW_ALL_ADMIN (owner of all RDS_RAW tables) attach these policies to
-- sensitive columns in a future migration, without needing MASKING_ADMIN itself.
GRANT APPLY ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_TEXT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN;
GRANT APPLY ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE.RDS_RAW.PII_MASK_BINARY
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN;
GRANT APPLY ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_TEXT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN;
GRANT APPLY ON MASKING POLICY SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW.PII_MASK_BINARY
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN;
