import datetime as dt
import argparse
import streamlit as st
import pandas as pd
from snowflake.snowpark import Session
from snowflake.snowpark.context import get_active_session


def read_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--local-dev",
        action="store_true",
        help=(
            "Run in local development mode. Creates a Snowflake session using the "
            "'default' connection from ~/.snowflake/connections.toml instead of "
            "the active Streamlit in Snowflake (SiS) session. "
            "Usage: streamlit run streamlit_app.py -- --local-dev"
        ),
    )
    return parser.parse_args()


def get_session(local_dev: bool) -> Session:
    if local_dev:
        return Session.builder.config("connection_name", "default").create()

    return get_active_session()


# Set page config
st.set_page_config(page_title="Python/Command Line Client Usage", layout="wide")

# Title
st.title("Python/Command Line Client Usage")
st.markdown(
    '<p style="color: #cc0000; font-size: 0.85rem; margin-top: -0.4rem;">'
    "This app is "
    '<a href="https://github.com/Sage-Bionetworks/snowflake/blob/dev/STREAMLIT.md" target="_blank">managed on Github</a>. '
    "Any local edits will not be retained."
    "</p>",
    unsafe_allow_html=True,
)

# Initialize session configured for generated Streamlit apps
args = read_args()
session = get_session(args.local_dev)
try:
    session.query_tag = "__generated_streamlit"
except Exception:
    pass

# Parameter input widgets arranged in a row
(param_col_1,) = st.columns(1)

with param_col_1:
    # Parameter: daterange (relative)
    st.markdown("**Date range**")
    default_start = dt.datetime.now().date() - dt.timedelta(days=1 * 28)
    default_end = dt.datetime.now().date()
    input_daterange = st.date_input(
        "Date range",
        value=(default_start, default_end),
        label_visibility="collapsed",
        key="daterange_param",
    )

st.markdown("---")


@st.cache_data(ttl="23h50m")
def execute_query(query: str) -> str:
    return session.sql(query).collect_nowait().query_id


def query_1_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
SELECT
    CLIENT,
    count(*) AS NUMBER_OF_CALLS,
    count(distinct user_id) AS NUMBER_OF_UNIQUE_USERS

FROM
    synapse_data_warehouse.synapse_event.access_event
where
    {expr_daterange}
GROUP BY
    CLIENT
ORDER BY
    NUMBER_OF_CALLS DESC;  """

    return sql_query


execute_query(query_1_1())


@st.fragment
def cell_1_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Client Usage Distribution")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_1_1",
                help="Refresh client_usage_distribution data",
            ):
                execute_query.clear(query_1_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_1_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            # Prepare data for bar chart
            if len(df) > 0:
                df = (
                    df.groupby(by="CLIENT", sort=False)
                    .agg(col1=("NUMBER_OF_CALLS", "sum"))
                    .rename(columns={"col1": "NUMBER_OF_CALLS (sum)"})
                    .reset_index()
                )

                df["/* Order Key (Generated by Snowflake) */"] = df.drop(
                    columns="CLIENT"
                ).sum(axis=1)

                datetime_primary_column = None
                if pd.api.types.is_datetime64_dtype(df["CLIENT"]):
                    datetime_primary_column = df["CLIENT"]
                elif df["CLIENT"].dtype == "object" and isinstance(
                    df["CLIENT"].get(df["CLIENT"].first_valid_index()), dt.date
                ):
                    datetime_primary_column = pd.to_datetime(
                        df["CLIENT"], errors="coerce"
                    )
                if (
                    datetime_primary_column is not None
                    and (
                        datetime_primary_column.max() - datetime_primary_column.min()
                    ).days
                    > len(df) * 2
                ):
                    # Use string type for sparse date range
                    df["CLIENT"] = df["CLIENT"].astype("string")

                st.bar_chart(
                    df,
                    x="CLIENT",
                    y=[
                        c
                        for c in df.columns
                        if c != "CLIENT"
                        and c != "/* Order Key (Generated by Snowflake) */"
                    ],
                    sort="-/* Order Key (Generated by Snowflake) */",
                    width="stretch",
                    height=400,
                    horizontal=True,
                    stack=False,
                )
            else:
                st.warning("No data available")
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_1_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
SELECT
    CLIENT,
    count(*) AS NUMBER_OF_CALLS,
    count(distinct user_id) AS NUMBER_OF_UNIQUE_USERS

FROM
    synapse_data_warehouse.synapse_event.access_event
where
    {expr_daterange}
GROUP BY
    CLIENT
ORDER BY
    NUMBER_OF_CALLS DESC;  """

    return sql_query


execute_query(query_1_2())


@st.fragment
def cell_1_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Client User Usage Distribution")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_1_2",
                help="Refresh client_user_usage_distribution data",
            ):
                execute_query.clear(query_1_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_1_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            # Prepare data for bar chart
            if len(df) > 0:
                df = df[["CLIENT", "NUMBER_OF_UNIQUE_USERS"]]

                df["/* Order Key (Generated by Snowflake) */"] = df.drop(
                    columns="CLIENT"
                ).sum(axis=1)

                datetime_primary_column = None
                if pd.api.types.is_datetime64_dtype(df["CLIENT"]):
                    datetime_primary_column = df["CLIENT"]
                elif df["CLIENT"].dtype == "object" and isinstance(
                    df["CLIENT"].get(df["CLIENT"].first_valid_index()), dt.date
                ):
                    datetime_primary_column = pd.to_datetime(
                        df["CLIENT"], errors="coerce"
                    )
                if (
                    datetime_primary_column is not None
                    and (
                        datetime_primary_column.max() - datetime_primary_column.min()
                    ).days
                    > len(df) * 2
                ):
                    # Use string type for sparse date range
                    df["CLIENT"] = df["CLIENT"].astype("string")

                st.bar_chart(
                    df,
                    x="CLIENT",
                    y=[
                        c
                        for c in df.columns
                        if c != "CLIENT"
                        and c != "/* Order Key (Generated by Snowflake) */"
                    ],
                    sort="-/* Order Key (Generated by Snowflake) */",
                    width="stretch",
                    height=400,
                    horizontal=True,
                    stack=False,
                )
            else:
                st.warning("No data available")
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 1: 2 Cells
col1_1, col1_2 = st.columns(2)
with col1_1:
    cell_1_1()
with col1_2:
    cell_1_2()


def query_2_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""



WITH logs AS (
    SELECT
        x_forwarded_for as ip
    FROM
        synapse_data_warehouse.synapse_event.access_event
    where
        {expr_daterange}
)

SELECT *
FROM logs l
JOIN TABLE(IP_INFO.public.GET_IP_LITE(l.ip));  """

    return sql_query


# Disabled intentionally: query_2_1 is too computationally expensive for routine UI execution.
# execute_query(query_2_1())


@st.fragment
def cell_2_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Copy of Client Usage Distribution")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_2_1",
                help="Refresh copy_of_client_usage_distribution data",
            ):
                # Disabled intentionally: do not clear or re-run query_2_1.
                # execute_query.clear(query_2_1())
                pass

        st.markdown(
            '<p style="color: #cc0000; font-size: 0.85rem; margin-top: -0.4rem;">'
            "This query has been disabled because <code>IP_INFO.PUBLIC.GET_IP_LITE</code> is too computationally intensive to evaluate on the result set within the warehouse timeout (3 hours)."
            "</p>",
            unsafe_allow_html=True,
        )


# Row 2: Single Cell
cell_2_1()


def query_3_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
SELECT
    count(*) AS NUMBER_OF_CALLS,
    count(distinct user_id) AS NUMBER_OF_UNIQUE_USERS

FROM
    synapse_data_warehouse.synapse_event.access_event
where
    {expr_daterange} and
    client in ('PYTHON', 'COMMAND_LINE')  """

    return sql_query


execute_query(query_3_1())


@st.fragment
def cell_3_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI client usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_3_1",
                help="Refresh py/cli_client_usage data",
            ):
                execute_query.clear(query_3_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_3_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_3_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
SELECT
    count(*) AS NUMBER_OF_CALLS,
    count(distinct user_id) AS NUMBER_OF_UNIQUE_USERS
FROM
    synapse_data_warehouse.synapse_event.access_event
JOIN
    SYNAPSE_DATA_WAREHOUSE.SYNAPSE.USERPROFILE_LATEST
    on access_event.user_id = userprofile_latest.id
where
    (
        userprofile_latest.email like '%@sagebase.org' or
        userprofile_latest.email like '%@sagebionetworks.org'
    ) and
    {expr_daterange} and
    client in ('PYTHON', 'COMMAND_LINE')  """

    return sql_query


execute_query(query_3_2())


@st.fragment
def cell_3_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI SAGE client usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_3_2",
                help="Refresh py/cli_sage_client_usage data",
            ):
                execute_query.clear(query_3_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_3_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 3: 2 Cells
col3_1, col3_2 = st.columns(2)
with col3_1:
    cell_3_1()
with col3_2:
    cell_3_2()


def query_4_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
with extract_version as (
    select
        user_agent, 
        COALESCE(
            client_version,
            -- SUBSTRING(
            --     user_agent,
            --     POSITION('synapseclient/' IN user_agent) + LENGTH('synapseclient/'),
            --     POSITION(' ' IN SUBSTRING(user_agent, POSITION('synapseclient/' IN user_agent) + LENGTH('synapseclient/'))) - 1
            -- )
            REGEXP_SUBSTR(
                user_agent,
                'synapseclient/([\\d\\.]+)',
                1,
                1,
                'e'
            )
    ) AS extracted_version
    from
        synapse_data_warehouse.synapse_event.access_event
    where
        client in ('PYTHON', 'COMMAND_LINE') and
        {expr_daterange}
)
select
    extracted_version,
    count(*) as number_of_calls
from
    extract_version
group by
    extract_version.extracted_version
order by
    number_of_calls DESC;

  """

    return sql_query


execute_query(query_4_1())


@st.fragment
def cell_4_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI Client Version Distribution")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_4_1",
                help="Refresh py/cli_client_version_distribution data",
            ):
                execute_query.clear(query_4_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_4_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            # Prepare data for bar chart
            if len(df) > 0:
                df = df[["EXTRACTED_VERSION", "NUMBER_OF_CALLS"]]

                df["/* Order Key (Generated by Snowflake) */"] = df.drop(
                    columns="EXTRACTED_VERSION"
                ).sum(axis=1)

                datetime_primary_column = None
                if pd.api.types.is_datetime64_dtype(df["EXTRACTED_VERSION"]):
                    datetime_primary_column = df["EXTRACTED_VERSION"]
                elif df["EXTRACTED_VERSION"].dtype == "object" and isinstance(
                    df["EXTRACTED_VERSION"].get(
                        df["EXTRACTED_VERSION"].first_valid_index()
                    ),
                    dt.date,
                ):
                    datetime_primary_column = pd.to_datetime(
                        df["EXTRACTED_VERSION"], errors="coerce"
                    )
                if (
                    datetime_primary_column is not None
                    and (
                        datetime_primary_column.max() - datetime_primary_column.min()
                    ).days
                    > len(df) * 2
                ):
                    # Use string type for sparse date range
                    df["EXTRACTED_VERSION"] = df["EXTRACTED_VERSION"].astype("string")

                st.bar_chart(
                    df,
                    x="EXTRACTED_VERSION",
                    y=[
                        c
                        for c in df.columns
                        if c != "EXTRACTED_VERSION"
                        and c != "/* Order Key (Generated by Snowflake) */"
                    ],
                    sort="-/* Order Key (Generated by Snowflake) */",
                    width="stretch",
                    height=400,
                    horizontal=True,
                    stack=False,
                )
            else:
                st.warning("No data available")
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_4_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
with extract_version as (
    select
        user_id,
        user_agent, 
        COALESCE(
            client_version,
            -- SUBSTRING(
            --     user_agent,
            --     POSITION('synapseclient/' IN user_agent) + LENGTH('synapseclient/'),
            --     POSITION(' ' IN SUBSTRING(user_agent, POSITION('synapseclient/' IN user_agent) + LENGTH('synapseclient/'))) - 1
            -- )
            REGEXP_SUBSTR(
                user_agent,
                'synapseclient/([\\d\\.]+)',
                1,
                1,
                'e'
            )
    ) AS extracted_version
    from
        synapse_data_warehouse.synapse_event.access_event
    where
        client in ('PYTHON', 'COMMAND_LINE') and
        extracted_version = '2.7.2' and
        {expr_daterange}
)
select
    extract_version.user_id,
    userprofile_latest.user_name,
    count(*) as number_of_calls
from
    extract_version
join
    synapse_data_warehouse.synapse.userprofile_latest
    on extract_version.user_id = userprofile_latest.id
group by
    extract_version.user_id, userprofile_latest.user_name
order by
    number_of_calls DESC;

  """

    return sql_query


execute_query(query_4_2())


@st.fragment
def cell_4_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI Users using v 2.7.2")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_4_2",
                help="Refresh py/cli_users_using_v_2.7.2 data",
            ):
                execute_query.clear(query_4_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_4_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            # Prepare data for bar chart
            if len(df) > 0:
                df = (
                    df.groupby(by="USER_NAME", sort=False)
                    .agg(col1=("NUMBER_OF_CALLS", "sum"))
                    .rename(columns={"col1": "NUMBER_OF_CALLS (sum)"})
                    .reset_index()
                )

                df["/* Order Key (Generated by Snowflake) */"] = df.drop(
                    columns="USER_NAME"
                ).sum(axis=1)

                datetime_primary_column = None
                if pd.api.types.is_datetime64_dtype(df["USER_NAME"]):
                    datetime_primary_column = df["USER_NAME"]
                elif df["USER_NAME"].dtype == "object" and isinstance(
                    df["USER_NAME"].get(df["USER_NAME"].first_valid_index()), dt.date
                ):
                    datetime_primary_column = pd.to_datetime(
                        df["USER_NAME"], errors="coerce"
                    )
                if (
                    datetime_primary_column is not None
                    and (
                        datetime_primary_column.max() - datetime_primary_column.min()
                    ).days
                    > len(df) * 2
                ):
                    # Use string type for sparse date range
                    df["USER_NAME"] = df["USER_NAME"].astype("string")

                st.bar_chart(
                    df,
                    x="USER_NAME",
                    y=[
                        c
                        for c in df.columns
                        if c != "USER_NAME"
                        and c != "/* Order Key (Generated by Snowflake) */"
                    ],
                    sort="-/* Order Key (Generated by Snowflake) */",
                    width="stretch",
                    height=400,
                    horizontal=True,
                    stack=False,
                )
            else:
                st.warning("No data available")
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 4: 2 Cells
col4_1, col4_2 = st.columns(2)
with col4_1:
    cell_4_1()
with col4_2:
    cell_4_2()


def query_5_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    NORMALIZED_METHOD_SIGNATURE,
    count(*) as number_of_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    client = 'PYTHON' and
    {expr_daterange}
group by 
    NORMALIZED_METHOD_SIGNATURE
order by
    number_of_calls DESC;  """

    return sql_query


execute_query(query_5_1())


@st.fragment
def cell_5_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI Distribution of endpoints called")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_5_1",
                help="Refresh py/cli_distribution_of_endpoints_called data",
            ):
                execute_query.clear(query_5_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_5_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 5: Single Cell
cell_5_1()


def query_6_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""

select
    response_status,
    count(*) as number_of_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    client in ('PYTHON', 'COMMAND_LINE') and
    {expr_daterange}
group by
    response_status
order by number_of_calls DESC;  """

    return sql_query


execute_query(query_6_1())


@st.fragment
def cell_6_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI Response status distribution")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_6_1",
                help="Refresh py/cli_response_status_distribution data",
            ):
                execute_query.clear(query_6_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_6_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_6_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""

select
    NORMALIZED_METHOD_SIGNATURE,
    response_status,
    count(*) as number_of_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    client in ('PYTHON', 'COMMAND_LINE') and
    {expr_daterange} and
    response_status BETWEEN 400 AND 500
group by
    NORMALIZED_METHOD_SIGNATURE, response_status
order by number_of_calls DESC;  """

    return sql_query


execute_query(query_6_2())


@st.fragment
def cell_6_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### PY/CLI errored response calls")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_6_2",
                help="Refresh py/cli_errored_response_calls data",
            ):
                execute_query.clear(query_6_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_6_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 6: 2 Cells
col6_1, col6_2 = st.columns(2)
with col6_1:
    cell_6_1()
with col6_2:
    cell_6_2()


def query_7_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
with extract_version as (
    select
        -- user_agent,
        -- client_version,
        case
            WHEN
                client_version like '%synapseclient%'
                THEN
                    REGEXP_SUBSTR(
                        user_agent,
                        'synapser/([\\d\\.]+)',
                        1,
                        1,
                        'e',
                        1
                    )
            ELSE client_version
        END as extracted_version
    from
        synapse_data_warehouse.synapse_event.access_event
    where
        client in ('SYNAPSER') and
        {expr_daterange}
)
select
    extracted_version,
    count(*) as number_of_calls
from
    extract_version
group by
    extract_version.extracted_version
order by
    number_of_calls DESC;

  """

    return sql_query


execute_query(query_7_1())


@st.fragment
def cell_7_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### R Client Version Distribution")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_7_1",
                help="Refresh r_client_version_distribution data",
            ):
                execute_query.clear(query_7_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_7_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            # Prepare data for bar chart
            if len(df) > 0:
                df = df[["EXTRACTED_VERSION", "NUMBER_OF_CALLS"]]

                df["/* Order Key (Generated by Snowflake) */"] = df.drop(
                    columns="EXTRACTED_VERSION"
                ).sum(axis=1)

                datetime_primary_column = None
                if pd.api.types.is_datetime64_dtype(df["EXTRACTED_VERSION"]):
                    datetime_primary_column = df["EXTRACTED_VERSION"]
                elif df["EXTRACTED_VERSION"].dtype == "object" and isinstance(
                    df["EXTRACTED_VERSION"].get(
                        df["EXTRACTED_VERSION"].first_valid_index()
                    ),
                    dt.date,
                ):
                    datetime_primary_column = pd.to_datetime(
                        df["EXTRACTED_VERSION"], errors="coerce"
                    )
                if (
                    datetime_primary_column is not None
                    and (
                        datetime_primary_column.max() - datetime_primary_column.min()
                    ).days
                    > len(df) * 2
                ):
                    # Use string type for sparse date range
                    df["EXTRACTED_VERSION"] = df["EXTRACTED_VERSION"].astype("string")

                st.bar_chart(
                    df,
                    x="EXTRACTED_VERSION",
                    y=[
                        c
                        for c in df.columns
                        if c != "EXTRACTED_VERSION"
                        and c != "/* Order Key (Generated by Snowflake) */"
                    ],
                    sort="-/* Order Key (Generated by Snowflake) */",
                    width="stretch",
                    height=400,
                    horizontal=True,
                    stack=False,
                )
            else:
                st.warning("No data available")
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_7_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""

select
    -- user_agent,
    -- client_version,
    distinct access_event.user_id, userprofile_latest.email
from
    synapse_data_warehouse.synapse_event.access_event
join
    synapse_data_warehouse.synapse.userprofile_latest
    on access_event.user_id = userprofile_latest.id
where
    client in ('SYNAPSER') and
    {expr_daterange}


  """

    return sql_query


execute_query(query_7_2())


@st.fragment
def cell_7_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### R client user emails")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_7_2",
                help="Refresh r_client_user_emails data",
            ):
                execute_query.clear(query_7_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_7_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 7: 2 Cells
col7_1, col7_2 = st.columns(2)
with col7_1:
    cell_7_1()
with col7_2:
    cell_7_2()


def query_8_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count(*) as number_of_calls,
    count(distinct user_id) as number_of_users
from
    synapse_data_warehouse.synapse_event.access_event
where
    client = 'PYTHON' and
    user_agent like '%iatlas%' and
    {expr_daterange}  """

    return sql_query


execute_query(query_8_1())


@st.fragment
def cell_8_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### iAtlas cbioportal pipeline")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_8_1",
                help="Refresh iatlas_cbioportal_pipeline data",
            ):
                execute_query.clear(query_8_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_8_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 8: Single Cell
cell_8_1()


def query_9_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count (distinct user_id) as number_of_unique_users,
    count(*) as number_of_api_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    user_agent like '%schematic/%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_9_1())


@st.fragment
def cell_9_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Schematic library Usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_9_1",
                help="Refresh schematic_library_usage data",
            ):
                execute_query.clear(query_9_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_9_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_9_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count(distinct user_id) as number_of_users,
    count(*) as number_of_api_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    oauth_client_id = 100311 and
    {expr_daterange}  """

    return sql_query


execute_query(query_9_2())


@st.fragment
def cell_9_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### DCA Usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_9_2",
                help="Refresh dca_usage data",
            ):
                execute_query.clear(query_9_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_9_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_9_3() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count(distinct user_id) as number_of_unique_users,
    count(*) as number_of_api_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    user_agent like '%schematiccommandline%' and
    {expr_daterange};

  """

    return sql_query


execute_query(query_9_3())


@st.fragment
def cell_9_3():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Schematic CLI usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_9_3",
                help="Refresh schematic_cli_usage data",
            ):
                execute_query.clear(query_9_3())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_9_3())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 9: 3 Cells
col9_1, col9_2, col9_3 = st.columns(3)
with col9_1:
    cell_9_1()
with col9_2:
    cell_9_2()
with col9_3:
    cell_9_3()


def query_10_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count(distinct user_id) as number_of_unique_users,
    count(*) as number_of_api_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    user_agent like '%synapsedesktopclient%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_10_1())


@st.fragment
def cell_10_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Desktop Client Usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_10_1",
                help="Refresh desktop_client_usage data",
            ):
                execute_query.clear(query_10_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_10_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_10_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    distinct user_id, userprofile_latest.email
from
    synapse_data_warehouse.synapse_event.access_event
join
    synapse_data_warehouse.synapse.userprofile_latest
    on access_event.user_id = userprofile_latest.id
where
    user_agent like '%synapsedesktopclient%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_10_2())


@st.fragment
def cell_10_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### Desktop Client Users")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_10_2",
                help="Refresh desktop_client_users data",
            ):
                execute_query.clear(query_10_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_10_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 10: 2 Cells
col10_1, col10_2 = st.columns(2)
with col10_1:
    cell_10_1()
with col10_2:
    cell_10_2()


def query_11_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count(distinct user_id) as number_of_unique_users,
    count(*) as number_of_api_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    user_agent like '%agora-data-tools%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_11_1())


@st.fragment
def cell_11_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### ADT Usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_11_1",
                help="Refresh adt_usage data",
            ):
                execute_query.clear(query_11_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_11_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_11_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    distinct user_id, userprofile_latest.email
from
    synapse_data_warehouse.synapse_event.access_event
join
    synapse_data_warehouse.synapse.userprofile_latest
    on access_event.user_id = userprofile_latest.id
where
    user_agent like '%agora-data-tools%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_11_2())


@st.fragment
def cell_11_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### ADT Users")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_11_2",
                help="Refresh adt_users data",
            ):
                execute_query.clear(query_11_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_11_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 11: 2 Cells
col11_1, col11_2 = st.columns(2)
with col11_1:
    cell_11_1()
with col11_2:
    cell_11_2()


def query_12_1() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    count(distinct user_id) as number_of_unique_users,
    count(*) as number_of_api_calls
from
    synapse_data_warehouse.synapse_event.access_event
where
    user_agent like '%aacrgenie%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_12_1())


@st.fragment
def cell_12_1():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### GENIE Usage")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_12_1",
                help="Refresh genie_usage data",
            ):
                execute_query.clear(query_12_1())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_12_1())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


def query_12_2() -> str:
    # Transform :daterange parameter - convert to range comparison
    if isinstance(input_daterange, tuple) and len(input_daterange) == 2:
        start_date, end_date = input_daterange
        expr_daterange = f"record_date BETWEEN '{start_date}' AND '{end_date}'"
    elif isinstance(input_daterange, tuple) and len(input_daterange) == 1:
        start_date = input_daterange[0]
        expr_daterange = f"record_date >= '{start_date}'"
    else:
        expr_daterange = "TRUE"

    sql_query = rf"""
select
    distinct user_id, userprofile_latest.email
from
    synapse_data_warehouse.synapse_event.access_event
join
    synapse_data_warehouse.synapse.userprofile_latest
    on access_event.user_id = userprofile_latest.id
where
    user_agent like '%aacrgenie%' and
    {expr_daterange};  """

    return sql_query


execute_query(query_12_2())


@st.fragment
def cell_12_2():
    with st.container(border=True):
        with st.container(
            horizontal=True,
            horizontal_alignment="distribute",
            vertical_alignment="center",
        ):
            with st.container(height=80, border=False, vertical_alignment="center"):
                st.markdown("### GENIE Users")
            if st.button(
                ":material/refresh:",
                type="tertiary",
                key=f"refresh_button_cell_12_2",
                help="Refresh genie_users data",
            ):
                execute_query.clear(query_12_2())

        try:
            with st.spinner("Executing query", show_time=True):
                df = session.create_async_job(execute_query(query_12_2())).result(
                    "pandas"
                )

            if any(df.columns.duplicated()):
                new_names = []
                name_indexes = {}
                for name in df.columns:
                    name_index = name_indexes.get(name, 0) + 1
                    name_indexes[name] = name_index
                    new_names.append(f"{name}_{name_index}" if name_index > 1 else name)
                df.columns = new_names

            if len(df) == 1 and len(df.columns) == 1:
                st.metric(
                    label=df.columns[0],
                    value=str(df.iloc[0, 0]),
                    label_visibility="collapsed",
                )
            else:
                st.dataframe(df, width="stretch", hide_index=True, height=400)
        except Exception as e:
            st.error(f"Error: {str(e)}")


# Row 12: 2 Cells
col12_1, col12_2 = st.columns(2)
with col12_1:
    cell_12_1()
with col12_2:
    cell_12_2()


# Footer
st.markdown("---")
st.markdown(
    "*Dashboard loaded: {}*".format(dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
)
