USE ROLE USERADMIN;

-- System-wide roles
CREATE OR ALTER ROLE MASKING_ADMIN;
CREATE OR ALTER ROLE DATA_ENGINEER;
CREATE OR ALTER ROLE DATA_ANALYTICS;
CREATE OR ALTER ROLE TASKADMIN;

-- DPE ops
CREATE OR ALTER ROLE DPE_OPS;

-- Project-specific roles
CREATE OR ALTER ROLE GENIE_ADMIN;
CREATE OR ALTER ROLE NF_ADMIN;
CREATE OR ALTER ROLE SCIDATA_ADMIN;
CREATE OR ALTER ROLE AD;
CREATE OR ALTER ROLE FAIR;
CREATE OR ALTER ROLE GOVERNANCE;
CREATE OR ALTER ROLE SAGE_LEADERS;

-- SYNAPSE_DATA_WAREHOUSE domain roles
CREATE OR ALTER ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN;
CREATE OR ALTER ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST;
CREATE OR ALTER ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN;
CREATE OR ALTER ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ANALYST;

-- Data Warehouse proxy admin roles
CREATE OR ALTER ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
CREATE OR ALTER ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;

-- SAGE.CITATIONS admin and analyst roles
CREATE OR ALTER ROLE SAGE_CITATIONS_ADMIN;
CREATE OR ALTER ROLE SAGE_CITATIONS_ANALYST;

-- SAGE.GOVERNANCE admin and analyst roles
CREATE OR ALTER ROLE SAGE_GOVERNANCE_ADMIN;
CREATE OR ALTER ROLE SAGE_GOVERNANCE_ANALYST;

-- SAGE DB Admin (parent of citations/governance/google_analytics admins)
CREATE OR ALTER ROLE SAGE_ADMIN;

-- GOOGLE_ANALYTICS_AGGREGATE roles
CREATE OR ALTER ROLE GOOGLE_ANALYTICS_AGGREGATE_ADMIN;

-- TECH_PRODUCT role for raw RDS snapshot access
CREATE OR ALTER ROLE TECH_PRODUCT;
