-- Future grants ensure that new objects created in each schema automatically
-- receive the correct ownership and read privileges without requiring manual
-- grant statements after each DDL operation.

-- ============================================================
-- SYNAPSE_DATA_WAREHOUSE — ownership future grants
-- ============================================================

-- SYNAPSE schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;

-- SYNAPSE_RAW schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;

-- SCHEMACHANGE schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_ALL_ADMIN;

-- SYNAPSE_AGGREGATE schema (tables owned by DB role; dynamic tables by proxy admin account role)
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;

-- SYNAPSE_EVENT schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_ADMIN;

-- RDS_LANDING schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_LANDING_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_LANDING_ALL_ADMIN;

-- RDS_RAW schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN;

-- ============================================================
-- SYNAPSE_DATA_WAREHOUSE — read future grants
-- ============================================================

-- SYNAPSE schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_TABLE_READ;
GRANT SELECT,
MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_TABLE_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_STAGE_READ;
GRANT SELECT,
REFERENCES ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_VIEW_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_TASK_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_FUNCTION_READ;

-- SYNAPSE_RAW schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_TABLE_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_STAGE_READ;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_STREAM_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_TASK_READ;

-- SCHEMACHANGE schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_TABLE_READ;

-- SYNAPSE_AGGREGATE schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_TABLE_READ;
GRANT SELECT,
MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_TABLE_READ;

-- SYNAPSE_EVENT schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_TABLE_READ;
GRANT SELECT,
MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_TABLE_READ;

-- RDS_LANDING schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_LANDING_TABLE_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_LANDING_STAGE_READ;

-- RDS_RAW schema
GRANT SELECT,
REFERENCES ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_VIEW_READ;

-- ============================================================
-- SYNAPSE_DATA_WAREHOUSE_DEV — ownership future grants
-- ============================================================

-- SYNAPSE schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;

-- SYNAPSE_RAW schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STREAMS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;

-- SCHEMACHANGE schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ADMIN;

-- SYNAPSE_AGGREGATE schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;

-- SYNAPSE_EVENT schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_ADMIN;

-- RDS_LANDING schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING_ALL_ADMIN;

-- RDS_RAW schema
GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN;
GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN;

-- ============================================================
-- SYNAPSE_DATA_WAREHOUSE_DEV — read future grants
-- ============================================================

-- SYNAPSE schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_TABLE_READ;
GRANT SELECT,
MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_TABLE_READ;
GRANT USAGE, READ ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_STAGE_READ;
GRANT SELECT,
REFERENCES ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_VIEW_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_TASK_READ;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_FUNCTION_READ;

-- SYNAPSE_RAW schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_TABLE_READ;
GRANT USAGE,
READ ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_STAGE_READ;
GRANT SELECT ON FUTURE STREAMS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_STREAM_READ;
GRANT MONITOR ON FUTURE TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_TASK_READ;

-- SCHEMACHANGE schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_TABLE_READ;

-- SYNAPSE_AGGREGATE schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_TABLE_READ;
GRANT SELECT,
MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_TABLE_READ;

-- SYNAPSE_EVENT schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_TABLE_READ;
GRANT SELECT,
MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_TABLE_READ;

-- RDS_LANDING schema
GRANT SELECT,
REFERENCES ON FUTURE TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING_TABLE_READ;
GRANT USAGE,
READ ON FUTURE STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING_STAGE_READ;

-- RDS_RAW schema
GRANT SELECT,
REFERENCES ON FUTURE VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_VIEW_READ;

-- ============================================================
-- SAGE database — future grants
-- ============================================================

GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SAGE.CITATIONS
TO ROLE SAGE_CITATIONS_ADMIN;
GRANT SELECT, REFERENCES ON FUTURE TABLES IN SCHEMA SAGE.CITATIONS
TO ROLE SAGE_CITATIONS_ANALYST;

GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA SAGE.GOVERNANCE
TO ROLE SAGE_GOVERNANCE_ADMIN;
GRANT SELECT, REFERENCES ON FUTURE TABLES IN SCHEMA SAGE.GOVERNANCE
TO ROLE SAGE_GOVERNANCE_ANALYST;

GRANT OWNERSHIP ON FUTURE DYNAMIC TABLES IN SCHEMA SAGE.GOVERNANCE
TO ROLE SAGE_GOVERNANCE_ADMIN;
GRANT SELECT, MONITOR ON FUTURE DYNAMIC TABLES IN SCHEMA SAGE.GOVERNANCE
TO ROLE SAGE_GOVERNANCE_ANALYST;
