USE ROLE SYSADMIN;

CREATE OR ALTER DATABASE GENIE;
CREATE OR ALTER DATABASE SAGE;
CREATE OR ALTER DATABASE DATA_ANALYTICS;
CREATE OR ALTER DATABASE SYNAPSE_DATA_WAREHOUSE;
CREATE OR ALTER DATABASE SYNAPSE_DATA_WAREHOUSE_DEV;
CREATE OR ALTER DATABASE METADATA;
