USE ROLE SYSADMIN;

-- Multi-cluster warehouse for general compute; MAX_CLUSTER_COUNT=50 for burst capacity
CREATE OR ALTER WAREHOUSE COMPUTE_XSMALL
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 70
AUTO_RESUME = TRUE
MAX_CLUSTER_COUNT = 50;

CREATE OR ALTER WAREHOUSE COMPUTE_MEDIUM
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = MEDIUM
AUTO_SUSPEND = 70
AUTO_RESUME = TRUE;

CREATE OR ALTER WAREHOUSE RECOVER_XSMALL
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 90
AUTO_RESUME = TRUE;

-- Extended auto-suspend to leverage Tableau query result caching
CREATE OR ALTER WAREHOUSE TABLEAU_XSMALL
WAREHOUSE_TYPE = STANDARD
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;
