-- ============================================================
-- ACCOUNTADMIN grants
-- ============================================================
USE ROLE ACCOUNTADMIN;

-- Task execution privileges
GRANT EXECUTE TASK, EXECUTE MANAGED TASK ON ACCOUNT TO ROLE TASKADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DATA_ENGINEER;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;

-- Serverless task execution for proxy admins
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;

-- Masking policy application
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE MASKING_ADMIN;

-- Account-level role grants to service accounts
GRANT ROLE ACCOUNTADMIN TO USER ADMIN_SERVICE;
GRANT ROLE DATA_ENGINEER TO USER DEVELOPER_SERVICE;

-- Application role revoke (GOOGLE_ANALYTICS share)
REVOKE APPLICATION ROLE GOOGLE_ANALYTICS.DATA_READER
    FROM ROLE DATA_ANALYTICS;

-- ============================================================
-- SECURITYADMIN grants
-- ============================================================
USE ROLE SECURITYADMIN;

-- ACCOUNTADMIN user grants
GRANT ROLE ACCOUNTADMIN TO USER "x.schildwachter@sagebase.org";
GRANT ROLE ACCOUNTADMIN TO USER "khai.do@sagebase.org";
GRANT ROLE ACCOUNTADMIN TO USER "phil.snyder@sagebase.org";

-- SYSADMIN user grants
GRANT ROLE SYSADMIN TO USER "x.schildwachter@sagebase.org";
GRANT ROLE SYSADMIN TO USER "phil.snyder@sagebase.org";
GRANT ROLE SYSADMIN TO USER DPE_SERVICE;

-- Role hierarchy: project roles roll up to SYSADMIN
GRANT ROLE GENIE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE AD TO ROLE SYSADMIN;
GRANT ROLE NF_ADMIN TO ROLE SYSADMIN;
GRANT ROLE SCIDATA_ADMIN TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYTICS TO ROLE SCIDATA_ADMIN;
GRANT ROLE DATA_ANALYTICS TO ROLE NF_ADMIN;
GRANT ROLE DATA_ANALYTICS TO ROLE GENIE_ADMIN;
GRANT ROLE DATA_ANALYTICS TO ROLE GOVERNANCE;
GRANT ROLE FAIR TO ROLE SYSADMIN;
GRANT ROLE DPE_OPS TO ROLE SYSADMIN;
GRANT ROLE GOVERNANCE TO ROLE SYSADMIN;
GRANT ROLE SAGE_LEADERS TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYTICS TO ROLE SAGE_LEADERS;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST TO ROLE SYNAPSE_DATA_WAREHOUSE_ADMIN;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST TO ROLE AD;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST TO ROLE GOVERNANCE;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST TO ROLE DATA_ANALYTICS;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST TO ROLE TECH_PRODUCT;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN TO ROLE SYSADMIN;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ANALYST TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ADMIN;
GRANT ROLE TASKADMIN TO ROLE DATA_ENGINEER;
GRANT ROLE SAGE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE SAGE_CITATIONS_ADMIN TO ROLE SAGE_ADMIN;
GRANT ROLE SAGE_GOVERNANCE_ADMIN TO ROLE SAGE_ADMIN;
GRANT ROLE GOOGLE_ANALYTICS_AGGREGATE_ADMIN TO ROLE SAGE_ADMIN;
GRANT ROLE SAGE_CITATIONS_ANALYST TO ROLE DATA_ANALYTICS;
GRANT ROLE SAGE_CITATIONS_ANALYST TO ROLE DATA_ENGINEER;
GRANT ROLE SAGE_GOVERNANCE_ANALYST TO ROLE GOVERNANCE;
GRANT ROLE SAGE_GOVERNANCE_ANALYST TO ROLE DATA_ENGINEER;
GRANT ROLE GOOGLE_ANALYTICS_AGGREGATE_ANALYST TO ROLE DATA_ENGINEER;
GRANT ROLE GOOGLE_ANALYTICS_AGGREGATE_ANALYST TO ROLE DATA_ANALYTICS;
GRANT ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST TO ROLE SAGE_GOVERNANCE_ADMIN;

-- Revoke DATA_ANALYTICS from AD (AD now gets access via SYNAPSE_DATA_WAREHOUSE_ANALYST)
REVOKE ROLE DATA_ANALYTICS FROM ROLE AD;

-- Masking policy schema privilege
GRANT CREATE MASKING POLICY ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO ROLE MASKING_ADMIN;

-- SECURITYADMIN schemachange metadata access
GRANT USAGE ON DATABASE METADATA TO ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA METADATA.SCHEMACHANGE TO ROLE SECURITYADMIN;
GRANT SELECT, INSERT ON TABLE METADATA.SCHEMACHANGE.CHANGE_HISTORY TO ROLE SECURITYADMIN;

-- User → role assignments: GENIE_ADMIN
GRANT ROLE GENIE_ADMIN TO USER "alexander.paynter@sagebase.org";
GRANT ROLE GENIE_ADMIN TO USER "xindi.guo@sagebase.org";
GRANT ROLE GENIE_ADMIN TO USER "chelsea.nayan@sagebase.org";
GRANT ROLE GENIE_ADMIN TO USER "rixing.xu@sagebase.org";
GRANT ROLE GENIE_ADMIN TO USER "adam.taylor@sagebase.org";
GRANT ROLE GENIE_ADMIN TO USER GENIE_SERVICE;

-- User → role assignments: AD
GRANT ROLE AD TO USER "samia.ahmed@sagebase.org";

-- User → role assignments: NF_ADMIN
GRANT ROLE NF_ADMIN TO USER "anh.nguyet.vu@sagebase.org";
GRANT ROLE NF_ADMIN TO USER "thomas.yu@sagebase.org";

-- User → role assignments: SCIDATA_ADMIN
GRANT ROLE SCIDATA_ADMIN TO USER "susheel.varma@sagebase.org";
GRANT ROLE SCIDATA_ADMIN TO USER "thomas.yu@sagebase.org";

-- User → role assignments: DATA_ENGINEER
GRANT ROLE DATA_ENGINEER TO USER "phil.snyder@sagebase.org";
GRANT ROLE DATA_ENGINEER TO USER "rixing.xu@sagebase.org";
GRANT ROLE DATA_ENGINEER TO USER "thomas.yu@sagebase.org";
GRANT ROLE DATA_ENGINEER TO USER "bryan.fauble@sagebase.org";
GRANT ROLE DATA_ENGINEER TO USER "nick.grosenbacher@sagebase.org";
GRANT ROLE DATA_ENGINEER TO USER "jenny.medina@sagebase.org";
GRANT ROLE DATA_ENGINEER TO USER DPE_SERVICE;

-- User → role assignments: DATA_ANALYTICS
GRANT ROLE DATA_ANALYTICS TO USER "diep.thach@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "rixing.xu@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "thomas.yu@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "anh.nguyet.vu@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "luca.foschini@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "xindi.guo@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "phil.snyder@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "chelsea.nayan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "alexander.paynter@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "x.schildwachter@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "natosha.edmonds@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "kevin.boske@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "robert.allaway@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "victor.baham@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "meghasyam@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "pranav.anbarasu@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "elias.chaibub.neto@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "bryan.fauble@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "john.hill@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "bruce.hoff@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "marco.marasca@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "sandhra.sokhal@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "adam.hindman@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jessica.malenfant@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "ann.novakowski@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "christine.suver@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "adam.taylor@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "sophia.jobe@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "thomas.schaffter@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "solly.sieberts@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "arti.singh@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "dan.lu@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jessica.britton@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "christina.conrad@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "drew.duglan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "zoe.leanza@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "anna.greenwood@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jay.hodgson@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "milan.vu@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "richard.yaxley@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "ashley.clayton@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "verena.chung@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jineta.banerjee@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jenny.medina@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "lakaija.johnson@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "sonia.carlson@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "anthony.williams@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "loren.wolfe@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "lingling.peng@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "gianna.jordan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "mieko.hashimoto@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "andrew.lamb@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "milen.nikolov@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "amy.heiser@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "rchai@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "maria.diaz@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "gaia.andreoletti@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "susheel.varma@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "amber.nelson@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "tiara.adams@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "william.poehlman@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "alberto.pepe@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jessica.vera@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "kimberly.corrigan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "mackenzie.wildman@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "aditi.gopalan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "angie.bowen@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "aditya.nath@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "james.moon@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "orion.banks@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "lisa.pasquale@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "JONI.HARKER@SAGEBASE.ORG";
GRANT ROLE DATA_ANALYTICS TO USER "jo.scanlan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "trisha.zintel@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "anthony.pena@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "hayley.sanchez@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "bishoy.kamel@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "andrea.varsavsky@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "serghei.mangul@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jaclyn.beck@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "ziwei.pan@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "karina.leal@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "ann.campton@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "savitha.sangameswaran@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "vanessa.barone@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jonathan.liaw-gray@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "laura.heath@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "melissa.klein@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "sarah.mansfield@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "andree-anne.berthiaume@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "dottie.young@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "jordan.driscoll@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "ram.ayyala@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "beatriz.saldana@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "tera.derita@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "belinda.garana@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "emma.costa@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "julia.gray@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "luisa.chekrygin@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "laurielle.roberson@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "samuel.cason@sagebase.org";
GRANT ROLE DATA_ANALYTICS TO USER "amelia.weixler@sagebase.org";

-- User → role assignments: SAGE_LEADERS
GRANT ROLE SAGE_LEADERS TO USER "kim.baggett@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "luca.foschini@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "alberto.pepe@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "susheel.varma@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "christine.suver@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "mackenzie.wildman@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "amy.heiser@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "brandon.morgan@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "thomas.yu@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "milen.nikolov@sagebase.org";
GRANT ROLE SAGE_LEADERS TO USER "andrea.varsavsky@sagebase.org";

-- User → role assignments: FAIR
GRANT ROLE FAIR TO USER "anthony.williams@sagebase.org";
GRANT ROLE FAIR TO USER "loren.wolfe@sagebase.org";
GRANT ROLE FAIR TO USER "lingling.peng@sagebase.org";
GRANT ROLE FAIR TO USER "gianna.jordan@sagebase.org";
GRANT ROLE FAIR TO USER "mieko.hashimoto@sagebase.org";
GRANT ROLE FAIR TO USER "andrew.lamb@sagebase.org";
GRANT ROLE FAIR TO USER "milen.nikolov@sagebase.org";
GRANT ROLE FAIR TO USER "amy.heiser@sagebase.org";

-- User → role assignments: DPE_OPS
GRANT ROLE DPE_OPS TO USER "thomas.yu@sagebase.org";
GRANT ROLE DPE_OPS TO USER "sophia.jobe@sagebase.org";

-- User → role assignments: GOVERNANCE
GRANT ROLE GOVERNANCE TO USER "christine.suver@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "kimberly.corrigan@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "ann.novakowski@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "anthony.pena@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "samia.ahmed@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "jonathan.liaw-gray@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "samuel.cason@sagebase.org";
GRANT ROLE GOVERNANCE TO USER "amelia.weixler@sagebase.org";

-- User → role assignments: MASKING_ADMIN
GRANT ROLE MASKING_ADMIN TO USER "thomas.yu@sagebase.org";

-- User → role assignments: TECH_PRODUCT
GRANT ROLE TECH_PRODUCT TO USER "christina.parry@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "kevin.boske@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "milen.nikolov@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "ann.novakowski@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "samia.ahmed@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "sophia.jobe@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "shaun.kalweit@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "thomas.yu@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "phil.snyder@sagebase.org";
GRANT ROLE TECH_PRODUCT TO USER "jenny.medina@sagebase.org";

-- ============================================================
-- SYSADMIN grants: warehouse usage
-- ============================================================
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_XSMALL TO ROLE DATA_ANALYTICS;
GRANT USAGE ON WAREHOUSE COMPUTE_XSMALL TO ROLE GOVERNANCE;
GRANT USAGE ON WAREHOUSE COMPUTE_XSMALL TO ROLE TECH_PRODUCT;
GRANT USAGE ON WAREHOUSE COMPUTE_XSMALL TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_XSMALL TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_MEDIUM TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_MEDIUM TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;
GRANT USAGE ON WAREHOUSE TABLEAU_XSMALL TO ROLE GENIE_ADMIN;

-- ============================================================
-- Database and schema privilege grants
-- ============================================================

-- SAGE database
GRANT USAGE ON DATABASE SAGE TO ROLE PUBLIC;
GRANT USAGE ON DATABASE SAGE TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE SAGE TO ROLE DATA_ANALYTICS;
GRANT USAGE ON DATABASE SAGE TO ROLE AD;
GRANT USAGE ON DATABASE SAGE TO ROLE SAGE_CITATIONS_ADMIN;
GRANT USAGE ON DATABASE SAGE TO ROLE SAGE_CITATIONS_ANALYST;
GRANT USAGE ON DATABASE SAGE TO ROLE SAGE_GOVERNANCE_ADMIN;
GRANT USAGE ON DATABASE SAGE TO ROLE SAGE_GOVERNANCE_ANALYST;

GRANT SELECT ON FUTURE TABLES IN SCHEMA SAGE.AD TO ROLE DATA_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAGE.AD TO ROLE DATA_ANALYTICS;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAGE.IT TO ROLE DATA_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAGE.IT TO ROLE DATA_ANALYTICS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SAGE.AUDIT TO ROLE DATA_ANALYTICS;

GRANT ALL PRIVILEGES ON SCHEMA SAGE.AD TO ROLE AD;
GRANT ALL PRIVILEGES ON SCHEMA SAGE.NF TO ROLE NF_ADMIN;
GRANT ALL PRIVILEGES ON SCHEMA SAGE.SCIDATA TO ROLE SCIDATA_ADMIN;

GRANT USAGE ON SCHEMA SAGE.CITATIONS TO ROLE SAGE_CITATIONS_ANALYST;
GRANT SELECT, REFERENCES ON TABLE SAGE.CITATIONS.AD_GOOGLE_SCHOLAR TO ROLE SAGE_CITATIONS_ANALYST;
GRANT SELECT, REFERENCES ON TABLE SAGE.CITATIONS.GENIE TO ROLE SAGE_CITATIONS_ANALYST;
GRANT SELECT, REFERENCES ON TABLE SAGE.CITATIONS.GENIE_GOOGLE_SCHOLAR TO ROLE SAGE_CITATIONS_ANALYST;
GRANT SELECT, REFERENCES ON TABLE SAGE.CITATIONS.SYNAPSE_MINTED_DOIS TO ROLE SAGE_CITATIONS_ANALYST;

GRANT USAGE ON SCHEMA SAGE.GOVERNANCE TO ROLE SAGE_GOVERNANCE_ANALYST;

-- Storage integration grants
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION SYNAPSE_PROD_WAREHOUSE_S3 TO ROLE SYSADMIN;
GRANT USAGE ON INTEGRATION SYNAPSE_PROD_WAREHOUSE_S3 TO ROLE DATA_ENGINEER;
GRANT USAGE ON INTEGRATION SYNAPSE_PROD_WAREHOUSE_S3 TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;
GRANT USAGE ON INTEGRATION SYNAPSE_DEV_WAREHOUSE_S3 TO ROLE SYSADMIN;
GRANT USAGE ON INTEGRATION SYNAPSE_DEV_WAREHOUSE_S3 TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;
GRANT USAGE ON INTEGRATION SYNAPSE_SNAPSHOTS_DEV TO ROLE DATA_ENGINEER;
GRANT USAGE ON INTEGRATION SYNAPSE_SNAPSHOTS_DEV TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;
GRANT USAGE ON INTEGRATION SYNAPSE_SNAPSHOTS_PROD TO ROLE DATA_ENGINEER;
GRANT USAGE ON INTEGRATION SYNAPSE_SNAPSHOTS_PROD TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;

USE ROLE SECURITYADMIN;

-- Shared/marketplace database privileges
GRANT IMPORTED PRIVILEGES ON DATABASE IP_INFO TO ROLE DATA_ENGINEER;
GRANT IMPORTED PRIVILEGES ON DATABASE IP_INFO TO ROLE GOVERNANCE;
GRANT IMPORTED PRIVILEGES ON DATABASE IP_INFO TO ROLE DATA_ANALYTICS;

GRANT USAGE ON ALL PROCEDURES IN DATABASE SYNAPSE_DATA_WAREHOUSE TO ROLE GOVERNANCE;

-- SYNAPSE_RDS_SNAPSHOT access for TECH_PRODUCT
GRANT USAGE ON DATABASE SYNAPSE_RDS_SNAPSHOT TO ROLE TECH_PRODUCT;
GRANT DATABASE ROLE SYNAPSE_RDS_SNAPSHOT.raw_table_read_censored TO ROLE TECH_PRODUCT;

-- ============================================================
-- SYNAPSE_DATA_WAREHOUSE database role grants
-- Grants aggregate database roles to their parent account roles
-- ============================================================

-- SYNAPSE schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ANALYST
    TO ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST;
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SYNAPSE_RAW schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SYNAPSE_AGGREGATE schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_ANALYST
    TO ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST;
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SYNAPSE_EVENT schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_ANALYST
    TO ROLE SYNAPSE_DATA_WAREHOUSE_ANALYST;
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SCHEMACHANGE schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_ALL_ANALYST
    TO ROLE DATA_ENGINEER;

-- ============================================================
-- SYNAPSE_DATA_WAREHOUSE_DEV database role grants
-- ============================================================

-- SYNAPSE schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ANALYST
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ANALYST;
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SYNAPSE_RAW schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SYNAPSE_AGGREGATE schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_ANALYST
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ANALYST;
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SYNAPSE_EVENT schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_ANALYST
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ANALYST;
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_DEVELOPER
    TO ROLE DATA_ENGINEER;

-- SCHEMACHANGE schema
GRANT DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ANALYST
    TO ROLE DATA_ENGINEER;

-- ============================================================
-- Schema-level privilege grants within SYNAPSE_DATA_WAREHOUSE
-- ============================================================

-- SYNAPSE schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ANALYST;

-- SYNAPSE_RAW schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_DEVELOPER;

-- SCHEMACHANGE schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_ALL_ANALYST;

-- SYNAPSE_AGGREGATE schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_ANALYST;
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_ALL_DEVELOPER;

-- SYNAPSE_EVENT schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_ANALYST;
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_DEVELOPER;

-- RDS_LANDING schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_LANDING
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_LANDING_ALL_DEVELOPER;

-- RDS_RAW schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_DEVELOPER;

-- Object-type-specific privilege grants: SYNAPSE schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_TABLE_READ;
GRANT SELECT, MONITOR ON ALL DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_TABLE_READ;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_STAGE_READ;
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_VIEW_READ;
GRANT MONITOR ON ALL TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_TASK_READ;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_FUNCTION_READ;

-- Object-type-specific privilege grants: SYNAPSE_RAW schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_TABLE_READ;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_STAGE_READ;
GRANT SELECT ON ALL STREAMS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_STREAM_READ;
GRANT MONITOR ON ALL TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_TASK_READ;

-- Object-type-specific privilege grants: SCHEMACHANGE schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_TABLE_READ;

-- Object-type-specific privilege grants: SYNAPSE_AGGREGATE schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_AGGREGATE_TABLE_READ;

-- Object-type-specific privilege grants: SYNAPSE_EVENT schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_TABLE_READ;

-- ============================================================
-- Schema-level privilege grants within SYNAPSE_DATA_WAREHOUSE_DEV
-- ============================================================

-- SYNAPSE schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ANALYST;

-- SYNAPSE_RAW schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_DEVELOPER;

-- SCHEMACHANGE schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ANALYST;

-- SYNAPSE_AGGREGATE schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_ANALYST;
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_ALL_DEVELOPER;

-- SYNAPSE_EVENT schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_ANALYST;
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_DEVELOPER;

-- RDS_LANDING schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_LANDING_ALL_DEVELOPER;

-- RDS_RAW schema
GRANT USAGE, MONITOR ON SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_DEVELOPER;

-- Object-type-specific privilege grants: SYNAPSE schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_TABLE_READ;
GRANT SELECT, MONITOR ON ALL DYNAMIC TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_TABLE_READ;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_STAGE_READ;
GRANT SELECT, REFERENCES ON ALL VIEWS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_VIEW_READ;
GRANT MONITOR ON ALL TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_TASK_READ;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_FUNCTION_READ;

-- Object-type-specific privilege grants: SYNAPSE_RAW schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_TABLE_READ;
GRANT USAGE, READ ON ALL STAGES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_STAGE_READ;
GRANT SELECT ON ALL STREAMS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_STREAM_READ;
GRANT MONITOR ON ALL TASKS IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_TASK_READ;

-- Object-type-specific privilege grants: SCHEMACHANGE schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_TABLE_READ;

-- Object-type-specific privilege grants: SYNAPSE_AGGREGATE schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_AGGREGATE_TABLE_READ;

-- Object-type-specific privilege grants: SYNAPSE_EVENT schema
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_TABLE_READ;
