USE ROLE ACCOUNTADMIN;
USE SCHEMA POLICY_DB.PUBLIC;

-- Password policy (CREATE OR ALTER not supported for PASSWORD POLICY; use IF NOT EXISTS)
CREATE PASSWORD POLICY IF NOT EXISTS password_policy
    PASSWORD_MIN_LENGTH = 14
    PASSWORD_MAX_AGE_DAYS = 0;

-- Session policy (CREATE OR ALTER not supported for SESSION POLICY; use IF NOT EXISTS)
CREATE SESSION POLICY IF NOT EXISTS admin_timeout_policy
    SESSION_IDLE_TIMEOUT_MINS = 15
    SESSION_UI_IDLE_TIMEOUT_MINS = 15;

-- Account-level tag for distinguishing service accounts
CREATE OR ALTER TAG ACCOUNT_TYPE;
ALTER USER IF EXISTS AD_SERVICE    SET TAG ACCOUNT_TYPE = 'service';
ALTER USER IF EXISTS DPE_SERVICE   SET TAG ACCOUNT_TYPE = 'service';
ALTER USER IF EXISTS SNOWFLAKE     SET TAG ACCOUNT_TYPE = 'service';
ALTER USER IF EXISTS thomasyu888   SET TAG ACCOUNT_TYPE = 'service';

-- Network policy (CREATE OR ALTER not supported for NETWORK POLICY; use IF NOT EXISTS)
CREATE NETWORK POLICY IF NOT EXISTS allow_all_ips
    ALLOWED_IP_LIST = ('0.0.0.0/0');

-- Authentication policies
CREATE OR ALTER AUTHENTICATION POLICY service_account_authentication_policy
    AUTHENTICATION_METHODS = ('PASSWORD', 'KEYPAIR');

CREATE OR ALTER AUTHENTICATION POLICY admin_authentication_policy
    AUTHENTICATION_METHODS = ('SAML', 'PASSWORD')
    SECURITY_INTEGRATIONS = ('GOOGLE_SSO', 'JUMPCLOUD');

CREATE OR ALTER AUTHENTICATION POLICY user_authentication_policy
    AUTHENTICATION_METHODS = ('SAML', 'KEYPAIR', 'PROGRAMMATIC_ACCESS_TOKEN')
    SECURITY_INTEGRATIONS = ('GOOGLE_SSO')
    PAT_POLICY = (
        DEFAULT_EXPIRY_IN_DAYS = 365,
        NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED
    );

-- Account-level settings
ALTER ACCOUNT SET ENABLE_IDENTIFIER_FIRST_LOGIN = TRUE;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';
ALTER ACCOUNT SET NETWORK_POLICY = allow_all_ips;
