USE SCHEMA {{database_name}}.synapse; --noqa: JJ01,PRS,TMP

-- Clone the CERTIFIEDQUIZQUESTIONS_LATEST table to ``CERTIFIEDQUIZQUESTIONS_LATEST_BACKUP``
-- This will begin the process of converting ``CERTIFIEDQUIZQUESTIONS_LATEST`` table into a dynamic table
CREATE OR REPLACE TABLE CERTIFIEDQUIZQUESTION_LATEST_BACKUP CLONE CERTIFIEDQUIZQUESTION_LATEST;
