USE SCHEMA {{database_name}}.synapse; --noqa: JJ01,PRS,TMP
CREATE OR REPLACE TABLE CERTIFIEDQUIZQUESTION_LATEST AS
WITH CQQ_RANKED AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY RESPONSE_ID, QUESTION_INDEX
            ORDER BY IS_CORRECT DESC, INSTANCE DESC
        ) AS ROW_NUM
    FROM {{database_name}}.SYNAPSE_RAW.CERTIFIEDQUIZQUESTIONSNAPSHOTS --noqa: TMP
)

SELECT * EXCLUDE ROW_NUM
FROM CQQ_RANKED
WHERE ROW_NUM = 1
ORDER BY RESPONSE_ID DESC, QUESTION_INDEX ASC;

-- Create certified quiz latest
CREATE OR REPLACE TABLE CERTIFIEDQUIZ_LATEST AS
WITH CQQ_RANKED AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY USER_ID
            ORDER BY INSTANCE DESC, RESPONSE_ID DESC
        ) AS ROW_NUM
    FROM {{database_name}}.SYNAPSE_RAW.CERTIFIEDQUIZSNAPSHOTS --noqa: TMP
)

SELECT * EXCLUDE ROW_NUM
FROM CQQ_RANKED
WHERE ROW_NUM = 1;
