GRANT OWNERSHIP
	ON FUTURE FUNCTIONS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE FUNCTIONS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT USAGE
	ON FUTURE FUNCTIONS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_FUNCTION_READ;
GRANT USAGE
	ON FUTURE FUNCTIONS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_FUNCTION_READ;
