GRANT OWNERSHIP
    ON FUTURE TABLES
    IN SCHEMA SAGE.CITATIONS
    TO ROLE SAGE_CITATIONS_ADMIN;
GRANT SELECT, REFERENCES
    ON FUTURE TABLES
    IN SCHEMA SAGE.CITATIONS
    TO ROLE SAGE_CITATIONS_ANALYST;