-- All privileges below are either excessive (e.g., write-type
-- privileges) or redundant with future grants already made
-- to the SYNAPSE_DATA_WAREHOUSE[_DEV]_ANALYST role.

-- SYNAPSE_DATA_WAREHOUSE --
REVOKE CREATE FUNCTION, CREATE STREAM, CREATE DYNAMIC TABLE, CREATE STREAMLIT, CREATE TABLE, CREATE TASK, MODIFY, USAGE, CREATE PROCEDURE, CREATE STAGE
	ON FUTURE SCHEMAS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE DATA_ENGINEER;
REVOKE SELECT, OPERATE, MONITOR
	ON FUTURE DYNAMIC TABLES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE DATA_ENGINEER;
REVOKE READ, USAGE, WRITE
	ON FUTURE STAGES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE DATA_ENGINEER;
REVOKE SELECT
	ON FUTURE STREAMS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE DATA_ENGINEER;
REVOKE EVOLVE SCHEMA, SELECT, UPDATE, INSERT
	ON FUTURE TABLES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE DATA_ENGINEER;
REVOKE APPLYBUDGET, MONITOR, OPERATE
	ON FUTURE TASKS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE DATA_ENGINEER;
REVOKE SELECT
	ON FUTURE DYNAMIC TABLES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE GOVERNANCE;
REVOKE USAGE
	ON FUTURE PROCEDURES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE GOVERNANCE;
REVOKE USAGE
	ON FUTURE SCHEMAS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE GOVERNANCE;
REVOKE SELECT
	ON FUTURE TABLES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE GOVERNANCE;
REVOKE SELECT
	ON FUTURE VIEWS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE
	FROM ROLE GOVERNANCE;

-- SYNAPSE_DATA_WAREHOUSE.SYNAPSE --
REVOKE SELECT
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	FROM ROLE AD;
REVOKE SELECT
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	FROM ROLE DATA_ANALYTICS;
REVOKE SELECT
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	FROM ROLE DATA_ANALYTICS;
REVOKE MONITOR, SELECT
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	FROM ROLE DATA_ENGINEER;
REVOKE SELECT
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	FROM ROLE PUBLIC;

-- SYNAPSE_DATA_WAREHOUSE_DEV --
REVOKE USAGE, CREATE DYNAMIC TABLE, CREATE FUNCTION, CREATE PROCEDURE, CREATE STAGE, CREATE STREAM, CREATE STREAMLIT, CREATE TABLE, CREATE TASK, MODIFY
	ON FUTURE SCHEMAS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
	FROM ROLE DATA_ENGINEER;
REVOKE OPERATE, SELECT, MONITOR
	ON FUTURE DYNAMIC TABLES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
	FROM ROLE DATA_ENGINEER;
REVOKE USAGE, WRITE, READ
	ON FUTURE STAGES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
	FROM ROLE DATA_ENGINEER;
REVOKE SELECT
	ON FUTURE STREAMS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
	FROM ROLE DATA_ENGINEER;
REVOKE EVOLVE SCHEMA, INSERT, SELECT, UPDATE
	ON FUTURE TABLES
	IN DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
	FROM ROLE DATA_ENGINEER;
REVOKE APPLYBUDGET, MONITOR, OPERATE
	ON FUTURE TASKS
	IN DATABASE SYNAPSE_DATA_WAREHOUSE_DEV
	FROM ROLE DATA_ENGINEER;

-- SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE --
REVOKE SELECT, MONITOR
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	FROM ROLE DATA_ENGINEER;