-- SYNAPSE_DATA_WAREHOUSE_DEV
-- admin/ownership
GRANT OWNERSHIP
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_ALL_ADMIN;
GRANT OWNERSHIP
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;

-- analyst/read
GRANT SELECT, REFERENCES
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_TABLE_READ;
GRANT SELECT, MONITOR
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_EVENT_TABLE_READ;

-- SYNAPSE_DATA_WAREHOUSE
-- admin/ownership
GRANT OWNERSHIP
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_ALL_ADMIN;
GRANT OWNERSHIP
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;

-- analyst/read
GRANT SELECT, REFERENCES
    ON FUTURE TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_TABLE_READ;
GRANT SELECT, MONITOR
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_EVENT_TABLE_READ;
