-- These object types don't yet exist in this schema.
-- We don't want to provide future grants unless there are preexisting objects.
REVOKE OWNERSHIP
	ON FUTURE STAGES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	FROM DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
REVOKE OWNERSHIP
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	FROM DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
REVOKE OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	FROM DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;