GRANT OWNERSHIP
    ON FUTURE TABLES
    IN SCHEMA SAGE.GOVERNANCE
    TO ROLE SAGE_GOVERNANCE_ADMIN;
GRANT SELECT, REFERENCES
    ON FUTURE TABLES
    IN SCHEMA SAGE.GOVERNANCE
    TO ROLE SAGE_GOVERNANCE_ANALYST;

GRANT OWNERSHIP
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SAGE.GOVERNANCE
    TO ROLE SAGE_GOVERNANCE_ADMIN;
GRANT SELECT, MONITOR
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SAGE.GOVERNANCE
    TO ROLE SAGE_GOVERNANCE_ANALYST;