GRANT OWNERSHIP
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_ALL_ADMIN;

GRANT OWNERSHIP
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_ALL_ADMIN;

GRANT SELECT, REFERENCES
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_VIEW_READ;

GRANT SELECT, REFERENCES
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_VIEW_READ;