-- Normalize future grants in SAGE.AD to schema admin and analyst roles only.

-- Revoke non-schema-role future grants in SAGE.AD
REVOKE ALL PRIVILEGES
    ON FUTURE TABLES
    IN SCHEMA SAGE.AD
    FROM ROLE DATA_ANALYTICS;
REVOKE ALL PRIVILEGES
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AD
    FROM ROLE DATA_ANALYTICS;
REVOKE ALL PRIVILEGES
    ON FUTURE TABLES
    IN SCHEMA SAGE.AD
    FROM ROLE SYSADMIN;
REVOKE ALL PRIVILEGES
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AD
    FROM ROLE SYSADMIN;

-- SAGE.AD analyst future grants
GRANT SELECT, REFERENCES
    ON FUTURE TABLES
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;
GRANT SELECT, REFERENCES
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;
GRANT USAGE, READ
    ON FUTURE STAGES
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;
GRANT USAGE
    ON FUTURE FILE FORMATS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;
GRANT USAGE
    ON FUTURE FUNCTIONS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;
GRANT USAGE
    ON FUTURE PROCEDURES
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;
GRANT USAGE
    ON FUTURE STREAMLITS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ANALYST;

-- SAGE.AD admin future ownership grants
GRANT OWNERSHIP
    ON FUTURE TABLES
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN;
GRANT OWNERSHIP
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN;
GRANT OWNERSHIP
    ON FUTURE STAGES
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN;
GRANT OWNERSHIP
    ON FUTURE FILE FORMATS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN;
GRANT OWNERSHIP
    ON FUTURE FUNCTIONS
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN;
GRANT OWNERSHIP
    ON FUTURE PROCEDURES
    IN SCHEMA SAGE.AD
    TO ROLE SAGE_AD_ADMIN;


