-- Normalize future grants in SAGE.AUDIT to schema admin and analyst roles only.

-- Revoke pre-existing non-schema-role future grants in SAGE.AUDIT
REVOKE ALL PRIVILEGES
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AUDIT
    FROM ROLE DATA_ANALYTICS;

-- SAGE.AUDIT analyst future grants
GRANT SELECT, REFERENCES
    ON FUTURE TABLES
    IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ANALYST;
GRANT SELECT, REFERENCES
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ANALYST;

-- SAGE.AUDIT admin future ownership grants
GRANT OWNERSHIP
    ON FUTURE TABLES
    IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ADMIN;
GRANT OWNERSHIP
    ON FUTURE VIEWS
    IN SCHEMA SAGE.AUDIT
    TO ROLE SAGE_AUDIT_ADMIN;
