-- Future ownership of Streamlit objects in SAGE.GOVERNANCE for the admin role,
-- and viewer access for the analyst role.
GRANT OWNERSHIP
    ON FUTURE STREAMLITS
    IN SCHEMA SAGE.GOVERNANCE
    TO ROLE SAGE_GOVERNANCE_ADMIN;
GRANT USAGE
    ON FUTURE STREAMLITS
    IN SCHEMA SAGE.GOVERNANCE
    TO ROLE SAGE_GOVERNANCE_ANALYST;
