-- Future grants for dynamic tables in RDS_RAW.
-- OWNERSHIP must go to the PROXY_ADMIN account role (not a database role) because
-- Snowflake requires account roles to own cross-schema objects like dynamic tables.
-- SELECT and MONITOR are granted to RDS_RAW_TABLE_READ so developers with the
-- RDS_RAW_ALL_DEVELOPER role can query and observe the dynamic tables.

-- Prod
GRANT OWNERSHIP
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
    TO ROLE SYNAPSE_DATA_WAREHOUSE_PROXY_ADMIN;

GRANT SELECT, MONITOR
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE.RDS_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.RDS_RAW_TABLE_READ;

-- Dev
GRANT OWNERSHIP
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
    TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_PROXY_ADMIN;

GRANT SELECT, MONITOR
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW
    TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.RDS_RAW_TABLE_READ;
