-- Future grants for dynamic tables in SAGE.CCKP.
-- USAGE on future Streamlits is already covered by V1.32.16.
GRANT OWNERSHIP
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SAGE.CCKP
    TO ROLE SAGE_CCKP_ADMIN;
GRANT SELECT
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SAGE.CCKP
    TO ROLE SAGE_CCKP_ANALYST;
GRANT MONITOR
    ON FUTURE DYNAMIC TABLES
    IN SCHEMA SAGE.CCKP
    TO ROLE SAGE_CCKP_ANALYST;
