---- SYNAPSE_DATA_WAREHOUSE ----
-- SYNAPSE
GRANT OWNERSHIP
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE STAGES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_ALL_ADMIN;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE STAGES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE STREAMS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW_ALL_ADMIN;

-- SCHEMACHANGE
GRANT OWNERSHIP
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.SCHEMACHANGE_ALL_ADMIN;

---- SYNAPSE_DATA_WAREHOUSE_DEV ----
-- SYNAPSE
GRANT OWNERSHIP
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE STAGES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE VIEWS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_ALL_ADMIN;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE STAGES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE STREAMS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;
GRANT OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW_ALL_ADMIN;

-- SCHEMACHANGE
GRANT OWNERSHIP
	ON FUTURE TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE_DEV.SCHEMACHANGE_ALL_ADMIN;