-- Grant future ownership of object types which potentially need
-- internamespace privileges to proxy admin database role.
-- SYNAPSE
GRANT OWNERSHIP
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.ALL_ADMIN;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE.SYNAPSE_RAW
	TO DATABASE ROLE SYNAPSE_DATA_WAREHOUSE.ALL_ADMIN;