-- Grant future ownership of object types which potentially need
-- internamespace privileges and/or account-level privileges to admin role.
-- SYNAPSE
GRANT OWNERSHIP
	ON FUTURE DYNAMIC TABLES
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE
	TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ALL_ADMIN;

-- SYNAPSE_RAW
GRANT OWNERSHIP
	ON FUTURE TASKS
	IN SCHEMA SYNAPSE_DATA_WAREHOUSE_DEV.SYNAPSE_RAW
	TO ROLE SYNAPSE_DATA_WAREHOUSE_DEV_ALL_ADMIN;