USE SCHEMA {{database_name}}.RDS_LANDING;
CREATE STAGE IF NOT EXISTS RDS_SNAPSHOTS_STAGE
    STORAGE_INTEGRATION = {{snapshots_stage_storage_integration}}
    URL = '{{snapshots_stage_url}}'
    FILE_FORMAT = (TYPE = PARQUET COMPRESSION = AUTO)
    DIRECTORY = (ENABLE = TRUE);
ALTER STAGE IF EXISTS RDS_SNAPSHOTS_STAGE REFRESH;
