USE SCHEMA {{database_name}}.synapse_raw; --noqa: JJ01,PRS,TMP

-- CREATE STREAM IF NOT EXISTS PROCESSEDACCESS_STREAM ON TABLE PROCESSEDACCESS;
-- CREATE STREAM IF NOT EXISTS FILEDOWNLOAD_STREAM ON TABLE FILEDOWNLOAD;
-- CREATE STREAM IF NOT EXISTS FILEUPLOAD_STREAM ON TABLE FILEUPLOAD;
CREATE STREAM IF NOT EXISTS ACLSNAPSHOTS_STREAM ON TABLE ACLSNAPSHOTS;
CREATE STREAM IF NOT EXISTS CERTIFIEDQUIZ_STREAM ON TABLE CERTIFIEDQUIZ;
CREATE STREAM IF NOT EXISTS CERTIFIEDQUIZQUESTION_STREAM ON TABLE CERTIFIEDQUIZQUESTION;
CREATE STREAM IF NOT EXISTS USERPROFILESNAPSHOT_STREAM ON TABLE USERPROFILESNAPSHOT;
CREATE STREAM IF NOT EXISTS TEAMMEMBERSNAPSHOTS_STREAM ON TABLE TEAMMEMBERSNAPSHOTS;
CREATE STREAM IF NOT EXISTS FILESNAPSHOTS_STREAM ON TABLE FILESNAPSHOTS;
CREATE STREAM IF NOT EXISTS NODESNAPSHOTS_STREAM ON TABLE NODESNAPSHOTS;
CREATE STREAM IF NOT EXISTS TEAMSNAPSHOTS_STREAM ON TABLE TEAMSNAPSHOTS;
CREATE STREAM IF NOT EXISTS USERGROUPSNAPSHOTS_STREAM ON TABLE USERGROUPSNAPSHOTS;
CREATE STREAM IF NOT EXISTS VERIFICATIONSUBMISSIONSNAPSHOTS_STREAM ON TABLE VERIFICATIONSUBMISSIONSNAPSHOTS;
