USE SCHEMA {{database_name}}.synapse_raw; --noqa: JJ01,PRS,TMP

CREATE OR REPLACE STREAM CERTIFIEDQUIZ_STREAM ON TABLE CERTIFIEDQUIZSNAPSHOTS;
CREATE OR REPLACE STREAM CERTIFIEDQUIZQUESTION_STREAM ON TABLE CERTIFIEDQUIZQUESTIONSNAPSHOTS;
