name: Snowflake Connection Test

on:
  push:
    branches:
      - 'snow-89-update-ci-with-service-user'

jobs:
  test-snowflake-connection:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
      SNOWSQL_USER: ${{ vars.ADMIN_SERVICE_USER }}
      SNOWSQL_WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}
      SNOWSQL_PRIVATE_KEY_PASSPHRASE: ${{ secrets.ADMIN_SERVICE_PRIVATE_PASS_PHRASE }}

    steps:
      - name: Write private key file
        run: |
          echo "${{ secrets.ADMIN_SERVICE_PRIVATE_KEY }}" > admin_service_key.p8
          chmod 400 admin_service_key.p8

      - name: Install SnowSQL
        run: |
            curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
            SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test connection
        run: |
          ~/bin/snowsql --private-key-path admin_service_key.p8 -q "SELECT CURRENT_USER(), CURRENT_ROLE();"