name: Snowflake Connection Test

on:
  push:
    branches:
      - 'snow-89-update-ci-with-service-user'

jobs:
    deploy-snowflake:
        name: Deploy Snowflake resources
        runs-on: ubuntu-latest
        env:
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.ADMIN_SERVICE_PASS_PHRASE }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Configure Snowflake connection
            run: |
              # Create temporary files for config.toml and our private key
              mkdir -p $HOME/.snowflake
              config_file=$HOME/.snowflake/config.toml
              private_key_file=$(mktemp)
            
              # Write to the private key file
              echo "${{ secrets.ADMIN_SERVICE_PRIVATE_KEY }}" > $private_key_file
                  
              # Write to config.toml file
              echo 'default_connection_name = "admin"' >> $config_file
              echo '[connections.admin]' >> $config_file
              echo "account = \"${{ secrets.SNOWSQL_ACCOUNT }}\"" >> $config_file
              echo "user = \"${{ vars.ADMIN_SERVICE_USER }}\"" >> $config_file
              echo 'warehouse = "${{ secrets.SNOWSQL_WAREHOUSE }}"' >> $config_file
              echo 'authenticator = "SNOWFLAKE_JWT"' >> $config_file
              echo "private_key_path = \"$private_key_file\"" >> $config_file

              # Restrict file owner read/write only (Snowflake requirement)
              chmod 0600 $config_file

          - name: Configuration file information
            run: |
              echo "Snowflake configuration is located at $config_file"
              cat $config_file
              
          - name: Install Snowflake CLI
            uses: Snowflake-Labs/snowflake-cli-action@v1.5

          - name: Test Snowflake connection
            run: |
              snow --version
              snow connection test
