name: Snowflake Connection Test

on:
  push:
    branches:
      - 'snow-89-update-ci-with-service-user'

jobs:
  deploy-snowflake-with-action:
    name: Deploy Snowflake resources with action
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_PASSPHRASE: ${{ secrets.ADMIN_SERVICE_PASS_PHRASE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: My action
        id: configure-snowflake
        uses: ./.github/actions/configure-snowflake-cli
        with:
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.ADMIN_SERVICE_PASS_PHRASE }}
          PRIVATE_KEY: ${{ secrets.ADMIN_SERVICE_PRIVATE_KEY }}
          ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          USER: ${{ vars.ADMIN_SERVICE_USER }}
          WAREHOUSE: ${{ secrets.SNOWSQL_WAREHOUSE }}

      - name: Print Snowflake CLI Version & Connection Status
        run: |
          echo "Config file path:"
          echo "${{ steps.configure-snowflake.outputs.config-file-path }}"
          echo "Connection file path:"
          echo "${{ steps.configure-snowflake.outputs.connection-file-path }}"
          echo "version:"
          echo "${{ steps.configure-snowflake.outputs.version }}"
          echo "connection:"
          echo "${{ steps.configure-snowflake.outputs.connection }}" | base64 --decode

      - name: deploy synapse_data_warehouse
        shell: bash
        run: |
          schemachange \
            -f analytics \
            -r SYSADMIN \
            -d SYNAPSE_DATA_WAREHOUSE_PHIL \
            --change-history-table SYNAPSE_DATA_WAREHOUSE_PHIL.SCHEMACHANGE.CHANGE_HISTORY \
            --connection-name default \
            --create-change-history-table