name: Test configure-snowflake-cli action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Configure Snowflake
        uses: ./.github/actions/configure-snowflake-cli
        with:
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.ADMIN_SERVICE_PASS_PHRASE }}
          PRIVATE_KEY: ${{ secrets.ADMIN_SERVICE_PRIVATE_KEY }}
          ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          USER: ${{ vars.ADMIN_SERVICE_USER }}

      - name: Verify uv version
        run: uv --version

      - name: Verify schemachange version
        run: schemachange --version
